"use client";

import { useState } from "react";

import { Button, Input } from "@orbit/ui";
import { cancelInterview, recordInterviewAttendance, saveInterviewNotes, saveOfficialInterviewResult } from "../../lib/api-client";

export function InterviewActions({ actorRole, id, version, status }: { actorRole: string; id: string; version: number; status: string }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState<string>(); const [notes, setNotes] = useState(""); const [result, setResult] = useState(""); const [cancelReason, setCancelReason] = useState("");
  async function run(action: () => Promise<unknown>) { setPending(true); setError(undefined); try { await action(); window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Interview action failed."); } finally { setPending(false); } }
  return <div className="mt-4 grid gap-3"><div className="flex flex-wrap gap-2">{actorRole === "CLOSER" && ["SCHEDULED", "RESCHEDULE_REQUIRED"].includes(status) ? <><Button disabled={pending} onClick={() => void run(() => recordInterviewAttendance(id, "ATTENDED", version))} size="sm">Mark attended</Button><Button disabled={pending} onClick={() => void run(() => recordInterviewAttendance(id, "MISSED", version))} size="sm" variant="ghost">Mark missed</Button></> : null}{actorRole !== "CLOSER" && status === "SCHEDULED" ? <div className="flex gap-2"><label className="sr-only" htmlFor={`cancel-${id}`}>Cancellation reason</label><Input id={`cancel-${id}`} onChange={(event) => setCancelReason(event.target.value)} placeholder="Cancellation reason" value={cancelReason} /><Button disabled={pending || !cancelReason.trim()} onClick={() => void run(() => cancelInterview(id, version, cancelReason))} size="sm" variant="ghost">Cancel</Button></div> : null}</div>{actorRole === "CLOSER" && (status === "COMPLETED" || status === "WAITING_FEEDBACK") ? <div className="grid gap-2 sm:grid-cols-[1fr_auto]"><label className="sr-only" htmlFor={`notes-${id}`}>Closer notes</label><Input id={`notes-${id}`} onChange={(event) => setNotes(event.target.value)} placeholder="Closer notes" value={notes} /><Button disabled={pending || !notes.trim()} onClick={() => void run(() => saveInterviewNotes(id, notes, version))} size="sm" variant="secondary">Save notes</Button></div> : null}{actorRole !== "CLOSER" && ["COMPLETED", "WAITING_FEEDBACK"].includes(status) ? <div className="grid gap-2 sm:grid-cols-[1fr_auto]"><label className="sr-only" htmlFor={`result-${id}`}>Official result</label><Input id={`result-${id}`} onChange={(event) => setResult(event.target.value)} placeholder="Official result" value={result} /><Button disabled={pending || !result.trim()} onClick={() => void run(() => saveOfficialInterviewResult(id, result, version))} size="sm" variant="secondary">Save result</Button></div> : null}{error ? <p className="text-sm font-semibold text-danger" role="alert">{error}</p> : null}</div>;
}
