export const ACTIVITY_ENTITY_TYPES = [
  "PROFILE",
  "LEAD",
  "INTERVIEW_ROUND",
  "USER",
] as const;

export const ACTIVITY_ACTIONS = [
  "PROFILE_CREATED",
  "PROFILE_UPDATED",
  "PROFILE_ASSIGNMENT_CHANGED",
  "LEAD_CREATED",
  "LEAD_UPDATED",
  "LEAD_STATUS_CHANGED",
  "LEAD_MARKED_IMPORTANT",
  "LEAD_UNMARKED_IMPORTANT",
  "LEAD_RATE_CHANGED",
  "LEAD_MARKED_DEAD",
  "LEAD_CLOSED",
  "INTERVIEW_ROUND_CREATED",
  "INTERVIEW_ROUND_UPDATED",
  "INTERVIEW_ROUND_RESULT_CHANGED",
  "USER_CREATED",
  "USER_DEACTIVATED",
  "USER_ROLE_CHANGED",
] as const;

export type ActivityEntityType = (typeof ACTIVITY_ENTITY_TYPES)[number];
export type ActivityAction = (typeof ACTIVITY_ACTIONS)[number];
