"use client";

import { useState } from "react";

import { Button, Card, Input } from "@orbit/ui";
import { createLeadComment, createLeadCommunication } from "../../lib/api-client";

export function CollaborationForm({ leadId, kind }: { leadId: string; kind: "comments" | "communications" }) {
  const [body, setBody] = useState(""); const [subject, setSubject] = useState(""); const [type, setType] = useState<"EMAIL" | "PHONE" | "LINKEDIN" | "JOB_PLATFORM" | "NOTE">("NOTE"); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); try { if (kind === "comments") await createLeadComment(leadId, { body, visibility: "INTERNAL_TEAM" }); else await createLeadCommunication(leadId, { type, direction: "INTERNAL", body, ...(subject.trim() ? { subject: subject.trim() } : {}), occurredAt: new Date().toISOString(), visibility: "INTERNAL_TEAM" }); window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The entry could not be saved."); } finally { setPending(false); } }
  return <Card className="p-5"><h2 className="text-base font-bold text-foreground">Add {kind === "comments" ? "comment" : "communication"}</h2><form className="mt-4 grid gap-3" onSubmit={submit}>{kind === "communications" ? <div className="grid gap-2 sm:grid-cols-[180px_1fr]"><label className="sr-only" htmlFor={`type-${leadId}`}>Communication type</label><select className="h-11 rounded-xl border border-border bg-surface px-3 text-sm" id={`type-${leadId}`} onChange={(event) => setType(event.target.value as typeof type)} value={type}><option value="NOTE">Note</option><option value="EMAIL">Email</option><option value="PHONE">Phone</option><option value="LINKEDIN">LinkedIn</option><option value="JOB_PLATFORM">Job platform</option></select><label className="sr-only" htmlFor={`subject-${leadId}`}>Subject</label><Input id={`subject-${leadId}`} onChange={(event) => setSubject(event.target.value)} placeholder="Subject (optional)" value={subject} /></div> : null}<label className="sr-only" htmlFor={`body-${leadId}`}>{kind === "comments" ? "Comment" : "Communication details"}</label><textarea className="min-h-28 rounded-xl border border-border bg-surface px-3.5 py-3 text-sm text-foreground outline-none focus:border-primary focus:ring-3 focus:ring-focus/15" id={`body-${leadId}`} onChange={(event) => setBody(event.target.value)} placeholder={kind === "comments" ? "Write an internal comment" : "Record what happened"} value={body} /><div className="flex items-center justify-between gap-3"><Button disabled={pending || !body.trim()} type="submit">{pending ? "Saving…" : "Save"}</Button>{error ? <p className="text-sm font-semibold text-danger" role="alert">{error}</p> : null}</div></form></Card>;
}
