import { availabilityExceptionInputSchema, availabilityRuleInputSchema, type AvailabilityExceptionInput, type AvailabilityRuleInput } from "@orbit/contracts";
import { AuthorizationError, NotFoundError, ValidationError } from "../errors/app-error";
import { AuthorizationService } from "../identity/authorization.service";
import type { Actor } from "../identity/session.service";
import type { LeadsDatabase } from "../leads/leads.service";

function invalid(issues: unknown) { return new ValidationError("The request payload is invalid", issues); }
function date(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
function rule(row: Record<string, unknown>) { return { id: String(row.id), closerId: String(row.closerId), dayOfWeek: Number(row.dayOfWeek), localStart: String(row.localStart), localEnd: String(row.localEnd), timezone: String(row.timezone), effectiveFrom: row.effectiveFrom ? date(row.effectiveFrom) : null, effectiveTo: row.effectiveTo ? date(row.effectiveTo) : null }; }
function exception(row: Record<string, unknown>) { return { id: String(row.id), closerId: String(row.closerId), startsAt: date(row.startsAt), endsAt: date(row.endsAt), type: row.type, reason: (row.reason as string | null) ?? null }; }

export class AvailabilityService {
  constructor(private readonly database: LeadsDatabase, private readonly authorization: AuthorizationService) {}
  async list(actor: Actor, closerId: string) { this.assertViewer(actor, closerId); const [rules, exceptions] = await Promise.all([this.database.availabilityRule.findMany({ where: { closerId }, orderBy: { dayOfWeek: "asc" } }), this.database.availabilityException.findMany({ where: { closerId }, orderBy: { startsAt: "asc" } })]); return { rules: rules.map(rule), exceptions: exceptions.map(exception) }; }
  async replaceRules(actor: Actor, closerId: string, inputs: AvailabilityRuleInput[]) { this.assertEditor(actor, closerId); if (!Array.isArray(inputs)) throw invalid([]); const parsed = inputs.map((input) => { const result = availabilityRuleInputSchema.safeParse(input); if (!result.success) throw invalid(result.error.issues); return result.data; }); await this.database.availabilityRule.deleteMany?.({ where: { closerId } }); for (const item of parsed) await this.database.availabilityRule.create({ data: { closerId, ...item, effectiveFrom: item.effectiveFrom ? new Date(item.effectiveFrom) : null, effectiveTo: item.effectiveTo ? new Date(item.effectiveTo) : null } }); await this.audit(actor, closerId, "availability.rules_replaced", closerId, "availability", { count: parsed.length }); return this.list(actor, closerId); }
  async addException(actor: Actor, input: AvailabilityExceptionInput) { this.assertEditor(actor, actor.id); const parsed = availabilityExceptionInputSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const row = await this.database.availabilityException.create({ data: { closerId: actor.id, ...parsed.data, startsAt: new Date(parsed.data.startsAt), endsAt: new Date(parsed.data.endsAt), reason: parsed.data.reason ?? null } }); await this.audit(actor, actor.id, "availability.exception_created", String(row.id), "availability_exception", { startsAt: row.startsAt, endsAt: row.endsAt, type: row.type }); return exception(row); }
  async updateException(actor: Actor, id: string, input: AvailabilityExceptionInput) { const current = await this.database.availabilityException.findUnique({ where: { id } }); if (!current) throw new NotFoundError("The availability exception was not found"); this.assertEditor(actor, String(current.closerId)); const parsed = availabilityExceptionInputSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const updated = await this.database.availabilityException.update!({ where: { id }, data: { ...parsed.data, startsAt: new Date(parsed.data.startsAt), endsAt: new Date(parsed.data.endsAt), reason: parsed.data.reason ?? null } }); await this.audit(actor, String(current.closerId), "availability.exception_updated", id, "availability_exception", { startsAt: updated.startsAt, endsAt: updated.endsAt, type: updated.type }); return exception(updated); }
  async removeException(actor: Actor, id: string) { const current = await this.database.availabilityException.findUnique({ where: { id } }); if (!current) throw new NotFoundError("The availability exception was not found"); this.assertEditor(actor, String(current.closerId)); await this.database.availabilityException.delete!({ where: { id } }); await this.audit(actor, String(current.closerId), "availability.exception_removed", id, "availability_exception", { startsAt: current.startsAt, endsAt: current.endsAt, type: current.type }); }
  private assertViewer(actor: Actor, closerId: string) { if (!actor.isActive || (actor.role === "CLOSER" && actor.id !== closerId)) throw new AuthorizationError(); }
  private assertEditor(actor: Actor, closerId: string) { if (!actor.isActive || (actor.role !== "ADMIN" && (actor.role !== "CLOSER" || actor.id !== closerId))) throw new AuthorizationError(); }
  private async audit(actor: Actor, closerId: string, action: string, entityId: string, entityType: string, newSnapshot: Record<string, unknown>) { await this.database.activityEvent.create({ data: { action, actorId: actor.id, actorNameSnapshot: actor.displayName, actorRoleSnapshot: actor.role, profileId: null, leadId: null, entityType, entityId, oldSnapshot: null, newSnapshot, metadata: { closerId }, requestId: null } }); }
}
