import { archiveCommunicationSchema, communicationListQuerySchema, createCommentSchema, createCommunicationSchema, updateCommentSchema, updateCommunicationSchema, type CommentSummary, type CommunicationListQuery, type CommunicationSummary, type CreateComment, type CreateCommunication, type UpdateComment, type UpdateCommunication } from "@orbit/contracts";
import { AuthorizationError, NotFoundError, StaleVersionError, ValidationError } from "../errors/app-error";
import { AuthorizationService } from "../identity/authorization.service";
import type { Actor as SessionActor } from "../identity/session.service";
import type { LeadsDatabase } from "./leads.service";
import { advanceLeadStatus } from "./lead-status";
import { assertCloserLeadAccess } from "./lead-access";

type FollowUpCompleter = {
  completeFollowUpFromCommunication(actor: SessionActor, leadId: string, communicationId: string, occurredAt: Date, database: unknown): Promise<unknown>;
};

function invalid(issues: unknown) { return new ValidationError("The request payload is invalid", issues); }
function iso(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
function communication(row: Record<string, unknown>): CommunicationSummary { return { id: String(row.id), leadId: String(row.leadId), contactId: (row.contactId as string | null) ?? null, authorId: String(row.authorId), type: row.type as CommunicationSummary["type"], direction: row.direction as CommunicationSummary["direction"], subject: (row.subject as string | null) ?? null, body: String(row.body), occurredAt: iso(row.occurredAt), outcome: (row.outcome as string | null) ?? null, visibility: row.visibility as CommunicationSummary["visibility"], nextActionSummary: (row.nextActionSummary as string | null) ?? null, nextActionDueAt: row.nextActionDueAt ? iso(row.nextActionDueAt) : null, archivedAt: row.archivedAt ? iso(row.archivedAt) : null, version: Number(row.version), createdAt: iso(row.createdAt), updatedAt: iso(row.updatedAt) }; }
function comment(row: Record<string, unknown>): CommentSummary { return { id: String(row.id), leadId: String(row.leadId), authorId: String(row.authorId), body: String(row.body), visibility: row.visibility as CommentSummary["visibility"], archivedAt: row.archivedAt ? iso(row.archivedAt) : null, createdAt: iso(row.createdAt), updatedAt: iso(row.updatedAt), version: Number(row.version) }; }

export class CollaborationService {
  constructor(private readonly database: LeadsDatabase, private readonly authorization: AuthorizationService, private readonly performance?: FollowUpCompleter) {}

  async listCommunications(actor: SessionActor, leadId: string, query: CommunicationListQuery) { const lead = await this.lead(actor, leadId); const parsed = communicationListQuerySchema.safeParse(query); if (!parsed.success) throw invalid(parsed.error.issues); const rows = await this.database.communication.findMany({ where: { leadId, ...(parsed.data.archived ? {} : { archivedAt: null }) }, orderBy: { occurredAt: "desc" }, take: parsed.data.limit }); return rows.filter((row) => actor.role !== "CLOSER" || row.visibility === "SHARED_WITH_CLOSER").map(communication); }
  async createCommunication(actor: SessionActor, leadId: string, input: CreateCommunication) { const lead = await this.lead(actor, leadId); this.assertBdEditor(actor, lead); const parsed = createCommunicationSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); if (parsed.data.contactId) { const contact = await this.database.contact.findFirst({ where: { id: parsed.data.contactId, companyId: lead.companyId } }); if (!contact) throw new NotFoundError("The selected contact was not found for this company"); } const created = await this.database.$transaction(async (transaction) => { const row = await transaction.communication.create({ data: { ...parsed.data, leadId, authorId: actor.id, occurredAt: new Date(parsed.data.occurredAt), nextActionDueAt: parsed.data.nextActionDueAt ? new Date(parsed.data.nextActionDueAt) : null, outcome: parsed.data.outcome ?? null, subject: parsed.data.subject ?? null, nextActionSummary: parsed.data.nextActionSummary ?? null } }); if (parsed.data.direction === "OUTBOUND") await this.performance?.completeFollowUpFromCommunication(actor, leadId, String(row.id), new Date(parsed.data.occurredAt), transaction); if (parsed.data.direction === "INBOUND") await advanceLeadStatus(transaction as never, actor, lead, "RESPONSE_RECEIVED", {}, "communication.inbound"); await this.audit(actor, lead, "communication.created", "communication", String(row.id), { body: row.body, type: row.type, contactId: row.contactId ?? null }, transaction as Pick<LeadsDatabase, "activityEvent">); return row; }); return communication(created); }
  async updateCommunication(actor: SessionActor, id: string, input: UpdateCommunication, expectedVersion: number) { const row = await this.require(this.database.communication, id, "communication"); const lead = await this.lead(actor, String(row.leadId)); this.assertBdEditor(actor, lead); const parsed = updateCommunicationSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const result = await this.database.communication.updateMany({ where: { id, version: expectedVersion }, data: { ...parsed.data, ...(parsed.data.occurredAt ? { occurredAt: new Date(parsed.data.occurredAt) } : {}), ...(parsed.data.nextActionDueAt !== undefined ? { nextActionDueAt: parsed.data.nextActionDueAt ? new Date(parsed.data.nextActionDueAt) : null } : {}), version: { increment: 1 } } }); if (!result.count) throw await this.stale(this.database.communication, id, expectedVersion, "communication"); const updated = await this.require(this.database.communication, id, "communication"); await this.audit(actor, lead, "communication.updated", "communication", id, parsed.data as Record<string, unknown>); return communication(updated); }
  async archiveCommunication(actor: SessionActor, id: string, reason: string) { const row = await this.require(this.database.communication, id, "communication"); const lead = await this.lead(actor, String(row.leadId)); this.assertBdEditor(actor, lead); const parsed = archiveCommunicationSchema.safeParse({ reason }); if (!parsed.success) throw invalid(parsed.error.issues); await this.database.communication.updateMany({ where: { id }, data: { archivedAt: new Date(), archiveReason: parsed.data.reason, version: { increment: 1 } } }); await this.audit(actor, lead, "communication.archived", "communication", id, { reason: parsed.data.reason }); }

  async listComments(actor: SessionActor, leadId: string) { await this.lead(actor, leadId); const rows = await this.database.comment.findMany({ where: { leadId, archivedAt: null }, orderBy: { createdAt: "asc" } }); return rows.filter((row) => actor.role !== "CLOSER" || row.visibility === "SHARED_WITH_CLOSER").map(comment); }
  async createComment(actor: SessionActor, leadId: string, input: CreateComment) { const lead = await this.lead(actor, leadId); const parsed = createCommentSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); if (actor.role === "CLOSER" && parsed.data.visibility !== "SHARED_WITH_CLOSER") throw new AuthorizationError(); const created = await this.database.comment.create({ data: { leadId, authorId: actor.id, ...parsed.data } }); await this.audit(actor, lead, "comment.created", "comment", String(created.id), { body: created.body, visibility: created.visibility }); return comment(created); }
  async updateComment(actor: SessionActor, id: string, input: UpdateComment) { const row = await this.require(this.database.comment, id, "comment"); const lead = await this.lead(actor, String(row.leadId)); if (row.authorId !== actor.id && actor.role !== "ADMIN") throw new AuthorizationError(); const parsed = updateCommentSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); if (actor.role === "CLOSER" && (row.visibility !== "SHARED_WITH_CLOSER" || parsed.data.visibility === "INTERNAL_TEAM")) throw new AuthorizationError(); const result = await this.database.comment.updateMany({ where: { id, version: parsed.data.expectedVersion }, data: { ...(parsed.data.body !== undefined ? { body: parsed.data.body } : {}), ...(parsed.data.visibility !== undefined ? { visibility: parsed.data.visibility } : {}), version: { increment: 1 } } }); if (!result.count) throw await this.stale(this.database.comment, id, parsed.data.expectedVersion, "comment"); const updated = await this.require(this.database.comment, id, "comment"); await this.audit(actor, lead, "comment.updated", "comment", id, parsed.data as Record<string, unknown>); return comment(updated); }

  private async lead(actor: SessionActor, id: string) { const lead = await this.database.jobLead.findUnique({ where: { id } }); if (!lead) throw new NotFoundError("The requested lead was not found"); await this.authorization.assertProfileAccess(actor, String(lead.profileId)); if (actor.role === "BD" && lead.currentOwnerId !== actor.id) throw new AuthorizationError(); await assertCloserLeadAccess(this.database, actor, lead); return lead; }
  private assertBdEditor(actor: SessionActor, lead: Record<string, unknown>) { if (!actor.isActive || actor.role === "CLOSER" || (actor.role === "BD" && lead.currentOwnerId !== actor.id)) throw new AuthorizationError(); }
  private async audit(actor: SessionActor, lead: Record<string, unknown>, action: string, entityType: string, entityId: string, newSnapshot: Record<string, unknown>, database: Pick<LeadsDatabase, "activityEvent"> = this.database) { await database.activityEvent.create({ data: { action, actorId: actor.id, actorNameSnapshot: actor.displayName, actorRoleSnapshot: actor.role, profileId: String(lead.profileId), leadId: String(lead.id), entityType, entityId, oldSnapshot: null, newSnapshot, metadata: null, requestId: null } }); }
  private async require(store: { findUnique(args: unknown): Promise<Record<string, unknown> | null> }, id: string, label: string) { const row = await store.findUnique({ where: { id } }); if (!row) throw new NotFoundError(`The requested ${label} was not found`); return row; }
  private async stale(store: { findUnique(args: unknown): Promise<Record<string, unknown> | null> }, id: string, expected: number, label: string) { const row = await store.findUnique({ where: { id } }); return row ? new StaleVersionError(expected, Number(row.version)) : new NotFoundError(`The requested ${label} was not found`); }
}
