import { archiveDocumentSchema, attachDocumentUsageSchema, createDocumentSchema, createDocumentVersionSchema, documentUploadIntentSchema, type CreateDocument, type CreateDocumentVersion, type DocumentSummary } from "@orbit/contracts";
import { AuthorizationError, ConflictError, NotFoundError, ValidationError } from "../errors/app-error";
import { AuthorizationService } from "../identity/authorization.service";
import type { Actor } from "../identity/session.service";
import type { LeadsDatabase } from "../leads/leads.service";
import type { ObjectStorage } from "../providers/storage.port";

function invalid(issues: unknown) { return new ValidationError("The request payload is invalid", issues); }
function iso(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
function document(row: Record<string, unknown>): DocumentSummary { return { id: String(row.id), profileId: String(row.profileId), type: row.type as DocumentSummary["type"], title: String(row.title), currentVersionId: (row.currentVersionId as string | null) ?? null, archivedAt: row.archivedAt ? iso(row.archivedAt) : null, version: Number(row.version), createdAt: iso(row.createdAt), updatedAt: iso(row.updatedAt), versions: Array.isArray(row.versions) ? row.versions.map((v) => ({ id: String(v.id), documentId: String(v.documentId), versionNumber: Number(v.versionNumber), storageKey: String(v.storageKey), originalFilename: String(v.originalFilename), mimeType: String(v.mimeType), sizeBytes: Number(v.sizeBytes), checksum: String(v.checksum), uploadedById: String(v.uploadedById), createdAt: iso(v.createdAt) })) : undefined }; }

export class DocumentsService {
  constructor(private readonly database: LeadsDatabase, private readonly authorization: AuthorizationService, private readonly storage?: ObjectStorage) {}
  async list(actor: Actor, profileId: string) { await this.authorization.assertProfileAccess(actor, profileId); const rows = await this.database.document.findMany({ where: { profileId, archivedAt: null }, include: { versions: { orderBy: { versionNumber: "desc" } } }, orderBy: { title: "asc" } }); return rows.map(document); }
  async create(actor: Actor, profileId: string, input: CreateDocument) { if (!actor.isActive || actor.role === "CLOSER") throw new AuthorizationError(); this.authorization.assertRole(actor, ["ADMIN", "BD"]); await this.authorization.assertProfileAccess(actor, profileId); const parsed = createDocumentSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const created = await this.database.document.create({ data: { profileId, type: parsed.data.type, title: parsed.data.title, createdById: actor.id, versions: { create: { versionNumber: 1, storageKey: parsed.data.storageKey, originalFilename: parsed.data.originalFilename, mimeType: parsed.data.mimeType, sizeBytes: parsed.data.sizeBytes, checksum: parsed.data.checksum, uploadedById: actor.id } } }, include: { versions: true } }); const version = Array.isArray(created.versions) ? created.versions[0] : null; if (version) await this.database.document.updateMany({ where: { id: created.id }, data: { currentVersionId: version.id } }); return document(created); }
  async createUploadIntent(actor: Actor, profileId: string, input: unknown) { if (!actor.isActive || actor.role === "CLOSER") throw new AuthorizationError(); await this.authorization.assertProfileAccess(actor, profileId); const parsed = documentUploadIntentSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); if (!this.storage) throw new ValidationError("Document storage is not configured"); return this.storage.createUploadIntent({ idempotencyKey: parsed.data.idempotencyKey, ownerUserId: actor.id, filename: parsed.data.filename, contentType: parsed.data.contentType, contentLength: parsed.data.contentLength }); }
  async addVersion(actor: Actor, documentId: string, input: CreateDocumentVersion) { const existing = await this.require(documentId); await this.authorization.assertProfileAccess(actor, String(existing.profileId)); if (!actor.isActive || actor.role === "CLOSER") throw new AuthorizationError(); if (existing.archivedAt) throw new ValidationError("Archived documents cannot receive new versions"); const parsed = createDocumentVersionSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const latest = await this.database.documentVersion.findFirst({ where: { documentId }, orderBy: { versionNumber: "desc" } }); const version = await this.database.documentVersion.create({ data: { documentId, versionNumber: Number(latest?.versionNumber ?? 0) + 1, ...parsed.data, uploadedById: actor.id } }); await this.database.document.updateMany({ where: { id: documentId, version: existing.version }, data: { currentVersionId: version.id, version: { increment: 1 } } }); return document(await this.require(documentId, true)); }
  async archive(actor: Actor, id: string, reason: string) { const existing = await this.require(id); this.authorization.assertRole(actor, ["ADMIN"]); const parsed = archiveDocumentSchema.safeParse({ reason }); if (!parsed.success) throw invalid(parsed.error.issues); await this.database.document.updateMany({ where: { id }, data: { archivedAt: new Date(), archiveReason: parsed.data.reason, version: { increment: 1 } } }); }
  async attachToLead(actor: Actor, leadId: string, versionId: string, usageType: string) { const lead = await this.database.jobLead.findUnique({ where: { id: leadId } }); if (!lead) throw new NotFoundError("The requested lead was not found"); await this.authorization.assertProfileAccess(actor, String(lead.profileId)); if (actor.role === "CLOSER" || (actor.role === "BD" && lead.currentOwnerId !== actor.id)) throw new AuthorizationError(); const parsed = attachDocumentUsageSchema.safeParse({ documentVersionId: versionId, usageType }); if (!parsed.success) throw invalid(parsed.error.issues); const version = await this.database.documentVersion.findUnique({ where: { id: parsed.data.documentVersionId }, include: { document: true } }); const versionDocument = version?.document as Record<string, unknown> | undefined; if (!version || !versionDocument || versionDocument.profileId !== lead.profileId) throw new NotFoundError("The document version was not found for this profile"); try { return await this.database.leadDocumentUsage.create({ data: { leadId, documentVersionId: parsed.data.documentVersionId, usageType: parsed.data.usageType, attachedById: actor.id } }); } catch (error) { if (typeof error === "object" && error && "code" in error && (error as { code: string }).code === "P2002") throw new ConflictError("This document is already attached to the lead"); throw error; } }
  async createDownloadUrl(actor: Actor, documentId: string, versionId: string) { const version = await this.database.documentVersion.findUnique({ where: { id: versionId }, include: { document: true } }); const versionDocument = version?.document as Record<string, unknown> | undefined; if (!version || !versionDocument || versionDocument.id !== documentId) throw new NotFoundError("The requested document version was not found"); await this.authorization.assertProfileAccess(actor, String(versionDocument.profileId)); if (!this.storage) throw new ValidationError("Document storage is not configured"); return { downloadUrl: await this.storage.createDownloadUrl(String(version.storageKey)), expiresAt: new Date(Date.now() + 5 * 60 * 1000) }; }
  private async require(id: string, includeVersions = false) { const row = await this.database.document.findUnique({ where: { id }, ...(includeVersions ? { include: { versions: true } } : {}) }); if (!row) throw new NotFoundError("The requested document was not found"); return row; }
}
