import { Body, Controller, Get, Inject, Param, Patch, Post, Query, Req, UseGuards } from "@nestjs/common";
import { AuthenticationError, InterviewsService, NotificationsService, ValidationError } from "@orbit/backend";
import { calendarQuerySchema, createInterviewSchema, interviewAttendanceSchema, interviewNotesSchema, interviewStatusActionSchema, officialResultSchema, reportInterviewConflictSchema, rescheduleInterviewSchema, updateInterviewSchema, uuidSchema } from "@orbit/contracts";
import { IdentityGuard, type AuthenticatedRequest } from "../identity/identity.guard";
type Schema<T> = { safeParse(value: unknown): { success: true; data: T } | { success: false; error: { issues: unknown } } };
function parse<T>(schema: Schema<T>, value: unknown): T { const result = schema.safeParse(value); if (!result.success) throw new ValidationError("The request payload is invalid", result.error.issues); return result.data; }
@Controller()
@UseGuards(IdentityGuard)
export class InterviewsController {
  constructor(@Inject(InterviewsService) private readonly interviews: InterviewsService, @Inject(NotificationsService) private readonly notifications: NotificationsService) {}
  @Get("calendar") calendar(@Query() query: unknown, @Req() request: AuthenticatedRequest) { return this.interviews.calendar(this.actor(request), parse(calendarQuerySchema, query)); }
  @Get("leads/:leadId/interview-rounds") list(@Param("leadId") leadId: string, @Req() request: AuthenticatedRequest) { return this.interviews.list(this.actor(request), parse(uuidSchema, leadId)); }
  @Post("leads/:leadId/interview-rounds") async create(@Param("leadId") leadId: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const round = await this.interviews.create(this.actor(request), parse(uuidSchema, leadId), parse(createInterviewSchema, input)); await this.notifications.createInApp({ idempotencyKey: `interview-scheduled:${round.id}`, recipientUserId: round.closerId, title: "Interview scheduled", message: `Round ${round.roundNumber} has been scheduled`, relatedEntityType: "interview_round", relatedEntityId: round.id }); return round; }
  @Patch("interview-rounds/:roundId") update(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.interviews.update(this.actor(request), parse(uuidSchema, id), parse(updateInterviewSchema, input)); }
  @Post("interview-rounds/:roundId/cancel") cancel(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(interviewStatusActionSchema, input); return this.interviews.cancel(this.actor(request), parse(uuidSchema, id), value.expectedVersion, value.reason); }
  @Post("interview-rounds/:roundId/reschedule") async reschedule(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const round = await this.interviews.reschedule(this.actor(request), parse(uuidSchema, id), parse(rescheduleInterviewSchema, input)); await this.notifications.createInApp({ idempotencyKey: `interview-rescheduled:${round.id}:${round.version}`, recipientUserId: round.closerId, title: "Interview rescheduled", message: `Round ${round.roundNumber} has a new time`, relatedEntityType: "interview_round", relatedEntityId: round.id }); return round; }
  @Post("interview-rounds/:roundId/report-conflict") conflict(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(reportInterviewConflictSchema, input); return this.interviews.reportConflict(this.actor(request), parse(uuidSchema, id), value.reason, value.alternatives, value.expectedVersion); }
  @Post("interview-rounds/:roundId/attendance") attendance(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(interviewAttendanceSchema, input); return this.interviews.attendance(this.actor(request), parse(uuidSchema, id), value.attendance, value.expectedVersion); }
  @Post("interview-rounds/:roundId/closer-notes") notes(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(interviewNotesSchema, input); return this.interviews.notes(this.actor(request), parse(uuidSchema, id), value.notes, value.expectedVersion); }
  @Post("interview-rounds/:roundId/official-result") official(@Param("roundId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(officialResultSchema, input); return this.interviews.officialResult(this.actor(request), parse(uuidSchema, id), value.result, value.expectedVersion); }
  private actor(request: AuthenticatedRequest) { if (!request.actor) throw new AuthenticationError(); return request.actor; }
}
