import { cancelTaskSchema, completeTaskSchema, createTaskSchema, taskListQuerySchema, updateTaskSchema, type CreateTask, type TaskListQuery, type TaskSummary, type UpdateTask } from "@orbit/contracts";
import { AuthorizationError, NotFoundError, StaleVersionError, ValidationError } from "../errors/app-error";
import { AuthorizationService } from "../identity/authorization.service";
import type { Actor as SessionActor } from "../identity/session.service";
import type { LeadsDatabase } from "../leads/leads.service";

function invalid(issues: unknown) { return new ValidationError("The request payload is invalid", issues); }
function iso(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
function task(row: Record<string, unknown>): TaskSummary { return { id: String(row.id), profileId: String(row.profileId), leadId: (row.leadId as string | null) ?? null, assigneeId: String(row.assigneeId), creatorId: String(row.creatorId), type: row.type as TaskSummary["type"], title: String(row.title), description: (row.description as string | null) ?? null, priority: row.priority as TaskSummary["priority"], status: row.status as TaskSummary["status"], dueAt: iso(row.dueAt), completedAt: row.completedAt ? iso(row.completedAt) : null, completedNotes: (row.completedNotes as string | null) ?? null, createdAt: iso(row.createdAt), updatedAt: iso(row.updatedAt), version: Number(row.version) }; }

export class TasksService {
  constructor(private readonly database: LeadsDatabase, private readonly authorization: AuthorizationService, private readonly now = () => new Date()) {}
  async list(actor: SessionActor, query: TaskListQuery) { if (!actor.isActive) throw new AuthorizationError(); const parsed = taskListQuerySchema.safeParse(query); if (!parsed.success) throw invalid(parsed.error.issues); const q = parsed.data; if (q.profileId) await this.authorization.assertProfileAccess(actor, q.profileId); const search = q.search?.trim(); const searchKey = search?.toUpperCase(); const typeMatch = searchKey === "FOLLOW_UP" || searchKey === "PREPARE_INTERVIEW" || searchKey === "GENERAL" ? searchKey : undefined; const priorityMatch = searchKey === "LOW" || searchKey === "MEDIUM" || searchKey === "HIGH" ? searchKey : undefined; const rows = await this.database.task.findMany({ where: { ...(q.profileId ? { profileId: q.profileId } : {}), ...(q.leadId ? { leadId: q.leadId } : {}), ...(q.assigneeId ? { assigneeId: q.assigneeId } : {}), ...(q.status ? { status: q.status } : {}), ...(q.overdue ? { status: "OPEN", dueAt: { lt: this.now() } } : {}), ...(search ? { OR: [{ title: { contains: search, mode: "insensitive" } }, { description: { contains: search, mode: "insensitive" } }, ...(typeMatch ? [{ type: { equals: typeMatch } }] : []), ...(priorityMatch ? [{ priority: { equals: priorityMatch } }] : []), { profile: { name: { contains: search, mode: "insensitive" } } }, { profile: { candidate: { firstName: { contains: search, mode: "insensitive" } } } }, { profile: { candidate: { lastName: { contains: search, mode: "insensitive" } } } } ] } : {}) }, orderBy: { dueAt: "asc" }, take: q.limit }); const visible = actor.role === "ADMIN" ? rows : rows.filter((row) => row.assigneeId === actor.id); return visible.map(task); }
  async create(actor: SessionActor, input: CreateTask) { if (!actor.isActive || actor.role === "CLOSER") throw new AuthorizationError(); const parsed = createTaskSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); await this.authorization.assertProfileAccess(actor, parsed.data.profileId); if (actor.role === "BD" && parsed.data.assigneeId !== actor.id) throw new AuthorizationError(); if (parsed.data.leadId) { const lead = await this.database.jobLead.findUnique({ where: { id: parsed.data.leadId } }); if (!lead || lead.profileId !== parsed.data.profileId) throw new ValidationError("The task lead must belong to the selected profile"); } const row = await this.database.task.create({ data: { ...parsed.data, creatorId: actor.id, dueAt: new Date(parsed.data.dueAt), description: parsed.data.description ?? null, leadId: parsed.data.leadId ?? null } }); await this.audit(actor, row, "task.created", { status: row.status, title: row.title }); return task(row); }
  async update(actor: SessionActor, id: string, input: UpdateTask) { const row = await this.require(id); if (actor.role !== "ADMIN" && row.assigneeId !== actor.id) throw new AuthorizationError(); const parsed = updateTaskSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const result = await this.database.task.updateMany({ where: { id, version: parsed.data.expectedVersion, status: "OPEN" }, data: { ...(parsed.data.assigneeId !== undefined ? { assigneeId: parsed.data.assigneeId } : {}), ...(parsed.data.title !== undefined ? { title: parsed.data.title } : {}), ...(parsed.data.description !== undefined ? { description: parsed.data.description } : {}), ...(parsed.data.priority !== undefined ? { priority: parsed.data.priority } : {}), ...(parsed.data.dueAt !== undefined ? { dueAt: new Date(parsed.data.dueAt) } : {}), version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, parsed.data.expectedVersion); const updated = await this.require(id); await this.audit(actor, updated, "task.updated", parsed.data as Record<string, unknown>); return task(updated); }
  async complete(actor: SessionActor, id: string, notes: string | undefined, expectedVersion: number) { const row = await this.require(id); if (actor.role !== "ADMIN" && row.assigneeId !== actor.id) throw new AuthorizationError(); const parsed = completeTaskSchema.safeParse({ notes, expectedVersion }); if (!parsed.success) throw invalid(parsed.error.issues); const result = await this.database.task.updateMany({ where: { id, version: expectedVersion, status: "OPEN" }, data: { status: "COMPLETED", completedAt: this.now(), completedNotes: parsed.data.notes ?? null, version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, expectedVersion); const updated = await this.require(id); await this.audit(actor, updated, "task.completed", { notes: parsed.data.notes ?? null }); return task(updated); }
  async cancel(actor: SessionActor, id: string, reason: string, expectedVersion: number) { const row = await this.require(id); if (actor.role !== "ADMIN" && row.assigneeId !== actor.id) throw new AuthorizationError(); const parsed = cancelTaskSchema.safeParse({ reason, expectedVersion }); if (!parsed.success) throw invalid(parsed.error.issues); const result = await this.database.task.updateMany({ where: { id, version: expectedVersion, status: "OPEN" }, data: { status: "CANCELED", canceledAt: this.now(), canceledReason: parsed.data.reason, version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, expectedVersion); const updated = await this.require(id); await this.audit(actor, updated, "task.cancelled", { reason: parsed.data.reason }); return task(updated); }
  private async require(id: string) { const row = await this.database.task.findUnique({ where: { id } }); if (!row) throw new NotFoundError("The requested task was not found"); return row; }
  private async stale(id: string, expected: number) { const row = await this.database.task.findUnique({ where: { id } }); return row ? new StaleVersionError(expected, Number(row.version)) : new NotFoundError("The requested task was not found"); }
  private async audit(actor: SessionActor, row: Record<string, unknown>, action: string, newSnapshot: Record<string, unknown>) { await this.database.activityEvent.create({ data: { action, actorId: actor.id, actorNameSnapshot: actor.displayName, actorRoleSnapshot: actor.role, profileId: String(row.profileId), leadId: row.leadId ? String(row.leadId) : null, entityType: "task", entityId: String(row.id), oldSnapshot: null, newSnapshot, metadata: null, requestId: null } }); }
}
