import type { PerformanceFollowUpWithLead, UserSummary } from "@orbit/contracts";

type ReassignmentAction = (formData: FormData) => void | Promise<void>;

function dateTime(value: string | null): string {
  return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "UTC" }).format(new Date(value)) : "Not set";
}

export function ReassignmentQueue({ followUps, owners, onReassign }: { followUps: PerformanceFollowUpWithLead[]; owners: UserSummary[]; onReassign: ReassignmentAction }) {
  return <section aria-label="Admin reassignment queue" className="rounded-[26px] border border-border bg-card p-5 shadow-sm sm:p-6">
    <header className="flex items-start justify-between gap-3"><div><h2 className="text-base font-bold text-foreground">Reassignment queue</h2><p className="mt-1 text-xs text-muted-foreground">Admin-owned handoffs while BD SLA is paused.</p></div><span className="rounded-full bg-danger-soft px-2.5 py-1 text-[11px] font-semibold text-danger">{followUps.length} open</span></header>
    {followUps.length === 0 ? <p className="mt-4 text-sm text-muted-foreground">No follow-ups need Admin reassignment.</p> : <ul className="mt-4 space-y-3">{followUps.map((followUp) => <li className="rounded-2xl border border-danger/25 bg-danger-soft/40 p-4" key={followUp.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><a className="text-sm font-bold text-foreground hover:text-primary" href={`/leads/${followUp.lead.id}`}>{followUp.lead.companyName} · {followUp.lead.jobTitle}</a><p className="mt-1 text-xs text-muted-foreground">BD SLA paused · Admin SLA {followUp.adminReassignmentBreachedAt ? "overdue" : "active"}</p></div><span className="rounded-full bg-danger px-2 py-1 text-[10px] font-bold uppercase text-danger-foreground">{followUp.status === "ADMIN_REASSIGNMENT_OVERDUE" ? "Admin reassignment overdue" : "Needs reassignment"}</span></div><p className="mt-3 text-xs text-muted-foreground">Admin SLA due: {dateTime(followUp.adminReassignmentSlaDueAt)}</p><form action={onReassign} className="mt-3 flex flex-wrap items-center gap-2"><input name="followUpId" type="hidden" value={followUp.id} /><input name="expectedVersion" type="hidden" value={followUp.version} /><label className="sr-only" htmlFor={`owner-${followUp.id}`}>New owner for {followUp.lead.companyName}</label><select className="min-w-40 rounded-xl border border-border bg-background px-3 py-2 text-xs text-foreground" defaultValue="" id={`owner-${followUp.id}`} name="newOwnerId" required><option disabled value="">Choose BD owner</option>{owners.map((owner) => <option value={owner.id} key={owner.id}>{owner.displayName}</option>)}</select><button className="rounded-xl bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground" type="submit">Reassign owner</button></form></li>)}</ul>}
  </section>;
}
