import { Body, Controller, Get, Inject, Param, Patch, Post, Req, UseGuards } from "@nestjs/common";
import { AuthenticationError, NotificationsService, OffersService, ValidationError } from "@orbit/backend";
import { createOfferSchema, offerDecisionSchema, placementDateSchema, startPlacementSchema, updateOfferSchema, uuidSchema } from "@orbit/contracts";
import { IdentityGuard, type AuthenticatedRequest } from "../identity/identity.guard";
type Schema<T> = { safeParse(value: unknown): { success: true; data: T } | { success: false; error: { issues: unknown } } };
function parse<T>(schema: Schema<T>, value: unknown): T { const result = schema.safeParse(value); if (!result.success) throw new ValidationError("The request payload is invalid", result.error.issues); return result.data; }
@Controller()
@UseGuards(IdentityGuard)
export class OffersController {
  constructor(@Inject(OffersService) private readonly offers: OffersService, @Inject(NotificationsService) private readonly notifications: NotificationsService) {}
  @Get("leads/:leadId/offers") list(@Param("leadId") id: string, @Req() request: AuthenticatedRequest) { return this.offers.list(this.actor(request), parse(uuidSchema, id)); }
  @Post("leads/:leadId/offers") async create(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const leadId = parse(uuidSchema, id); const offer = await this.offers.create(this.actor(request), leadId, parse(createOfferSchema, input)); await this.notifications.notifyLeadOwner(leadId, { idempotencyKey: `offer-created:${offer.id}`, title: "New offer received", message: "An offer is ready for review", relatedEntityType: "offer", relatedEntityId: offer.id }); return offer; }
  @Patch("offers/:offerId") update(@Param("offerId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.offers.update(this.actor(request), parse(uuidSchema, id), parse(updateOfferSchema, input)); }
  @Post("offers/:offerId/decision") async decide(@Param("offerId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(offerDecisionSchema, input); const offer = await this.offers.decide(this.actor(request), parse(uuidSchema, id), value.decision, value.expectedVersion); await this.notifications.notifyLeadOwner(offer.leadId, { idempotencyKey: `offer-decision:${offer.id}:${offer.version}`, title: value.decision === "ACCEPTED" ? "Offer accepted" : "Offer declined", message: `The offer decision is ${value.decision.toLowerCase()}`, relatedEntityType: "offer", relatedEntityId: offer.id }); return offer; }
  @Post("offers/:offerId/place") async place(@Param("offerId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(placementDateSchema, input); const offer = await this.offers.place(this.actor(request), parse(uuidSchema, id), value.startDate, value.expectedVersion); await this.notifications.notifyLeadOwner(offer.leadId, { idempotencyKey: `offer-placed:${offer.id}:${offer.version}`, title: "Placement confirmed", message: `Start date: ${offer.startDate ?? "pending"}`, relatedEntityType: "offer", relatedEntityId: offer.id }); return offer; }
  @Post("offers/:offerId/start") async start(@Param("offerId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(startPlacementSchema, input); const offer = await this.offers.start(this.actor(request), parse(uuidSchema, id), value.expectedVersion); await this.notifications.notifyLeadOwner(offer.leadId, { idempotencyKey: `offer-started:${offer.id}:${offer.version}`, title: "Placement started", message: "The candidate has started the placement", relatedEntityType: "offer", relatedEntityId: offer.id }); return offer; }
  private actor(request: AuthenticatedRequest) { if (!request.actor) throw new AuthenticationError(); return request.actor; }
}
