import { createOfferSchema, offerDecisionSchema, placementDateSchema, startPlacementSchema, updateOfferSchema, type CreateOffer, type OfferSummary } from "@orbit/contracts";
import { AuthorizationError, ConflictError, NotFoundError, StaleVersionError, ValidationError } from "../errors/app-error";
import { AuthorizationService } from "../identity/authorization.service";
import type { Actor } from "../identity/session.service";
import type { LeadsDatabase } from "../leads/leads.service";
import { advanceLeadStatus } from "../leads/lead-status";

function invalid(issues: unknown) { return new ValidationError("The request payload is invalid", issues); }
function iso(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
function dateOnly(value: unknown) { return value instanceof Date ? value.toISOString().slice(0, 10) : value == null ? null : String(value); }
function offer(row: Record<string, unknown>): OfferSummary { return { id: String(row.id), leadId: String(row.leadId), status: row.status as OfferSummary["status"], compensationAmount: String(row.compensationAmount), compensationCurrency: String(row.compensationCurrency), employmentType: String(row.employmentType), details: String(row.details), decisionDeadline: row.decisionDeadline ? iso(row.decisionDeadline) : null, acceptedAt: row.acceptedAt ? iso(row.acceptedAt) : null, startDate: dateOnly(row.startDate), startedAt: row.startedAt ? iso(row.startedAt) : null, createdById: String(row.createdById), version: Number(row.version), createdAt: iso(row.createdAt), updatedAt: iso(row.updatedAt) }; }

export class OffersService {
  constructor(private readonly database: LeadsDatabase, private readonly authorization: AuthorizationService, private readonly now = () => new Date()) {}
  async list(actor: Actor, leadId: string) { const lead = await this.lead(actor, leadId); const rows = await this.database.offer.findMany({ where: { leadId }, orderBy: { createdAt: "desc" } }); return rows.map(offer); }
  async create(actor: Actor, leadId: string, input: CreateOffer) { const lead = await this.lead(actor, leadId); this.assertEditor(actor, lead); const parsed = createOfferSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const row = await this.database.offer.create({ data: { leadId, ...parsed.data, decisionDeadline: parsed.data.decisionDeadline ? new Date(parsed.data.decisionDeadline) : null, createdById: actor.id } }); await advanceLeadStatus(this.database as never, actor, lead, "OFFER_RECEIVED", {}, "offer.created"); await this.audit(actor, lead, "offer.created", String(row.id), { status: row.status, compensationAmount: row.compensationAmount }); return offer(row); }
  async update(actor: Actor, id: string, input: Record<string, unknown>) { const current = await this.require(id); const lead = await this.lead(actor, String(current.leadId)); this.assertEditor(actor, lead); const parsed = updateOfferSchema.safeParse(input); if (!parsed.success) throw invalid(parsed.error.issues); const result = await this.database.offer.updateMany({ where: { id, version: parsed.data.expectedVersion, status: "OFFERED" }, data: { ...Object.fromEntries(Object.entries(parsed.data).filter(([key, value]) => key !== "expectedVersion" && value !== undefined)), ...(parsed.data.decisionDeadline !== undefined ? { decisionDeadline: parsed.data.decisionDeadline ? new Date(parsed.data.decisionDeadline) : null } : {}), version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, parsed.data.expectedVersion); const updated = await this.require(id); await this.audit(actor, lead, "offer.updated", id, parsed.data as Record<string, unknown>); return offer(updated); }
  async decide(actor: Actor, id: string, decision: "ACCEPTED" | "DECLINED", expectedVersion: number) { const current = await this.require(id); const lead = await this.lead(actor, String(current.leadId)); this.assertEditor(actor, lead); const parsed = offerDecisionSchema.safeParse({ decision, expectedVersion }); if (!parsed.success) throw invalid(parsed.error.issues); const result = await this.database.offer.updateMany({ where: { id, version: expectedVersion, status: "OFFERED" }, data: { status: parsed.data.decision, ...(parsed.data.decision === "ACCEPTED" ? { acceptedAt: this.now() } : {}), version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, expectedVersion); if (decision === "ACCEPTED") await advanceLeadStatus(this.database as never, actor, lead, "OFFER_ACCEPTED", {}, "offer.accepted"); await this.audit(actor, lead, `offer.${decision.toLowerCase()}`, id, { decision }); return offer(await this.require(id)); }
  async place(actor: Actor, id: string, startDate: string, expectedVersion: number) { const current = await this.require(id); const lead = await this.lead(actor, String(current.leadId)); this.assertEditor(actor, lead); const parsed = placementDateSchema.safeParse({ startDate, expectedVersion }); if (!parsed.success) throw invalid(parsed.error.issues); if (current.status !== "ACCEPTED") throw new ConflictError("Only an accepted offer can become a placement"); const placedStartDate = new Date(`${parsed.data.startDate}T00:00:00.000Z`); const result = await this.database.offer.updateMany({ where: { id, version: expectedVersion, status: "ACCEPTED" }, data: { startDate: placedStartDate, version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, expectedVersion); await advanceLeadStatus(this.database as never, actor, lead, "PLACED", { startDate: placedStartDate }, "placement.confirmed"); await this.audit(actor, lead, "placement.confirmed", id, { startDate: parsed.data.startDate }); return offer(await this.require(id)); }
  async start(actor: Actor, id: string, expectedVersion: number) { const current = await this.require(id); const lead = await this.lead(actor, String(current.leadId)); this.assertEditor(actor, lead); const parsed = startPlacementSchema.safeParse({ expectedVersion }); if (!parsed.success) throw invalid(parsed.error.issues); if (current.startedAt) throw new ConflictError("This placement has already started"); if (current.status !== "ACCEPTED" || !current.startDate) throw new ConflictError("A confirmed placement date is required before starting"); const startedAt = this.now(); const result = await this.database.offer.updateMany({ where: { id, version: expectedVersion, status: "ACCEPTED", startedAt: null }, data: { startedAt, version: { increment: 1 } } }); if (!result.count) throw await this.stale(id, expectedVersion); await advanceLeadStatus(this.database as never, actor, lead, "STARTED", { startedAt }, "placement.started"); await this.audit(actor, lead, "placement.started", id, { startedAt }); return offer(await this.require(id)); }
  private async lead(actor: Actor, id: string) { const lead = await this.database.jobLead.findUnique({ where: { id } }); if (!lead) throw new NotFoundError("The requested lead was not found"); await this.authorization.assertProfileAccess(actor, String(lead.profileId)); if (actor.role === "BD" && lead.currentOwnerId !== actor.id) throw new AuthorizationError(); if (actor.role === "CLOSER") throw new AuthorizationError(); return lead; }
  private assertEditor(actor: Actor, lead: Record<string, unknown>) { if (!actor.isActive || actor.role === "CLOSER" || (actor.role === "BD" && lead.currentOwnerId !== actor.id)) throw new AuthorizationError(); }
  private async require(id: string) { const row = await this.database.offer.findUnique({ where: { id } }); if (!row) throw new NotFoundError("The requested offer was not found"); return row; }
  private async stale(id: string, expected: number) { const row = await this.database.offer.findUnique({ where: { id } }); return row ? new StaleVersionError(expected, Number(row.version)) : new NotFoundError("The requested offer was not found"); }
  private async audit(actor: Actor, lead: Record<string, unknown>, action: string, entityId: string, newSnapshot: Record<string, unknown>) { await this.database.activityEvent.create({ data: { action, actorId: actor.id, actorNameSnapshot: actor.displayName, actorRoleSnapshot: actor.role, profileId: String(lead.profileId), leadId: String(lead.id), entityType: "offer", entityId, oldSnapshot: null, newSnapshot, metadata: null, requestId: null } }); }
}
