import type { BdPerformanceResponse, InterviewSummary, LeadSummary, SessionUser, TaskSummary } from "@orbit/contracts";
import { Card } from "@orbit/ui";

import { BdPeerRanking } from "../performance/bd-peer-ranking";
import { BdPersonalQuality } from "../performance/bd-personal-quality";

type BdDashboardProps = {
  actor: SessionUser;
  applications: LeadSummary[];
  openTasks: TaskSummary[];
  interviews: InterviewSummary[];
  performance?: BdPerformanceResponse;
  todayPerformance?: BdPerformanceResponse;
  error?: string;
};

function interviewTime(interview: InterviewSummary): string {
  return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false, timeZone: interview.timezone }).format(new Date(interview.startsAt));
}

export function BdDashboard({ actor, applications, openTasks, interviews, performance, todayPerformance, error }: BdDashboardProps) {
  const now = new Date();
  const today = new Intl.DateTimeFormat("en-CA").format(now);
  const responses = applications.filter((application) => application.status === "RESPONSE_RECEIVED");
  const active = applications.filter((application) => ["INTERVIEWING", "OFFER_RECEIVED", "OFFER_ACCEPTED", "PLACED"].includes(application.status));
  const upcoming = interviews.filter((interview) => new Date(interview.startsAt) >= now).sort((left, right) => new Date(left.startsAt).getTime() - new Date(right.startsAt).getTime()).slice(0, 5);
  const dailyTarget = performance?.currentDailyTarget ?? 70;
  const qualifiedToday = todayPerformance?.performance.qualifiedApplications ?? applications.filter((application) => application.appliedDate === today).length;
  const interviewsToSchedule = todayPerformance?.performance.interviewsNeedingScheduling ?? responses.length;
  const kpis = [
    ["Qualified applications today", qualifiedToday, "bg-primary-soft", "text-primary", "/leads"],
    ["Remaining target", Math.max(0, dailyTarget - qualifiedToday), "bg-warning-soft", "text-warning-foreground", "/leads"],
    ["Recruiter responses", todayPerformance?.performance.recruiterResponses ?? responses.length, "bg-info-soft", "text-info", "/leads?status=RESPONSE_RECEIVED"],
    ["Interviews to schedule", interviewsToSchedule, "bg-danger-soft", "text-danger", "/leads?status=RESPONSE_RECEIVED"],
  ] as const;
  const platformCounts = new Map<string, number>();
  applications.forEach((application) => { try { const host = new URL(application.rawUrl).hostname.replace(/^www\./, ""); platformCounts.set(host, (platformCounts.get(host) ?? 0) + 1); } catch { platformCounts.set("Other", (platformCounts.get("Other") ?? 0) + 1); } });
  return <div aria-label="BD application workspace" className="editorial-dashboard mx-auto max-w-[1500px]">
    <div className="editorial-hero"><div className="editorial-date-rail"><span className="editorial-date-number">{new Intl.DateTimeFormat("en-US", { day: "2-digit" }).format(now)}</span><span><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short", month: "long" }).format(now)}</strong><small>Daily target · {dailyTarget}</small></span><a aria-label="Add application" className="editorial-add-button" href="/leads?new=application">+ Add application <span aria-hidden="true">›</span></a><a aria-label="Open full calendar" className="editorial-round-button" href="/calendar">□</a></div><div className="editorial-greeting"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">BD application desk</p><h1>Good morning, {actor.displayName.split(" ")[0]}</h1><p>Keep applications moving from entry to recruiter response.</p></div></div>
    {error ? <p className="mt-4 rounded-xl border border-warning/30 bg-warning-soft px-4 py-3 text-sm text-warning-foreground" role="status">{error}</p> : null}
    <section aria-label="BD application pulse" className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-foreground">Application pulse</h2><a className="text-xs font-semibold text-primary" href="/leads">Open all applications →</a></div><div className="editorial-pulse-grid">{kpis.map(([label, value, iconTone, valueTone, href]) => <a aria-label={`${label}: ${value}`} className="editorial-pulse-card" href={href} key={label}><span className={`editorial-pulse-icon ${iconTone} ${valueTone}`}>{label === "Recruiter responses" ? "↗" : label === "Interviews to schedule" ? "!" : "✓"}</span><span className="editorial-pulse-copy"><small>{label}</small><strong className={valueTone}>{value}</strong></span><span className="editorial-pulse-badge">{label === "Remaining target" ? `Target ${dailyTarget}` : "View"}</span></a>)}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,0.65fr)]"><Card aria-label="BD work queue" className="editorial-attention-card p-5 sm:p-6"><header className="flex items-center justify-between"><div><h2 className="text-base font-bold text-foreground">Work queue</h2><p className="mt-1 text-xs text-muted-foreground">The next operational handoffs.</p></div><a className="editorial-today-pill" href="/tasks">{openTasks.length} tasks</a></header><div className="mt-5 space-y-2.5"><a className="editorial-attention-item editorial-attention-danger" href="/leads?status=RESPONSE_RECEIVED"><span className="editorial-status-dot bg-danger" /><span><strong>Recruiter responses</strong><small>Review and schedule interviews.</small></span><b>{responses.length}</b></a><a className="editorial-attention-item" href="/leads?status=INTERVIEWING"><span className="editorial-status-dot bg-primary" /><span><strong>Active applications</strong><small>Already moving through the funnel.</small></span><b>{active.length}</b></a><a className="editorial-attention-item" href="/tasks"><span className="editorial-status-dot bg-warning" /><span><strong>Follow-ups due</strong><small>Keep recruiter conversations warm.</small></span><b>{openTasks.length}</b></a></div></Card>{performance ? <BdPersonalQuality performance={performance} /> : null}</div>
    <section aria-label="BD operations" className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(280px,0.65fr)]"><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><div><h2 className="text-base font-bold text-foreground">Recent applications</h2><p className="mt-1 text-xs text-muted-foreground">Latest entries needing a quick check.</p></div><a className="text-xs font-semibold text-primary" href="/leads">View all</a></header><div className="mt-4 divide-y divide-border">{applications.slice(0, 6).map((application) => <a className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0 hover:bg-surface-subtle" href={`/leads/${application.id}`} key={application.id}><span className="min-w-0"><strong className="block truncate text-sm text-foreground">{application.jobTitle}</strong><small className="block truncate text-xs text-muted-foreground">{application.companyName ?? "Company not recorded"} · {application.appliedDate}</small></span><span className="shrink-0 rounded-full bg-info-soft px-2.5 py-1 text-[10px] font-bold uppercase text-info">{application.status.replaceAll("_", " ")}</span></a>)}{applications.length === 0 ? <p className="py-5 text-sm text-muted-foreground">Your application entries will appear here.</p> : null}</div></Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><div><h2 className="text-base font-bold text-foreground">Upcoming interviews</h2><p className="mt-1 text-xs text-muted-foreground">Compact handoff view.</p></div><a className="text-xs font-semibold text-primary" href="/calendar">Open calendar</a></header>{upcoming.length ? <ol className="mt-4 divide-y divide-border">{upcoming.map((interview) => <li className="py-3 first:pt-0 last:pb-0" key={interview.id}><strong className="block truncate text-sm text-foreground">{interview.roundType.replaceAll("_", " ")}</strong><small className="block text-xs text-muted-foreground">{interviewTime(interview)} · {interview.timezone}</small><div className="mt-2 flex flex-wrap gap-3 text-xs font-semibold text-primary"><a href={`/leads/${interview.leadId}/interviews?edit=${interview.id}`}>Edit</a><a href={`/leads/${interview.leadId}`}>Open application</a><a href={`/calendar?date=${encodeURIComponent(interview.startsAt)}`}>Open calendar</a></div></li>)}</ol> : <p className="mt-5 text-sm text-muted-foreground">No upcoming interviews.</p>}</Card></section>
    <section aria-label="BD insights" className="mt-5 grid gap-5 md:grid-cols-2"><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Applications by platform</h2><span className="editorial-today-pill">{applications.length} total</span></header><ul className="mt-4 space-y-3">{Array.from(platformCounts.entries()).slice(0, 5).map(([platform, count]) => <li className="flex items-center justify-between text-sm" key={platform}><span className="text-muted-foreground">{platform}</span><strong>{count}</strong></li>)}</ul></Card>{performance ? <BdPeerRanking peers={performance.peerLeaderboard} selfRank={performance.rank} /> : <Card className="editorial-insight-card p-5 sm:p-6"><h2 className="text-base font-bold text-foreground">What needs attention</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Recruiter replies become active applications. Review the response, add interview details, then hand the scheduled call to the assigned Closer.</p></Card>}</section>
  </div>;
}
