import type { ActivityEventSummary, AdminBdPerformanceResponse, InterviewSummary, LeadSummary, PerformanceDrilldownResponse, PerformanceFollowUpWithLead, SessionUser, TaskSummary, UserSummary } from "@orbit/contracts";
import { Card } from "@orbit/ui";
import type { DashboardData } from "../../lib/api-client";
import { CalendarWorkspace } from "../calendar/calendar-workspace";
import { BdLeaderboard } from "../performance/bd-leaderboard";
import { BdTeamKpis, type PerformancePeriod } from "../performance/bd-team-kpis";
import { BuildingBaseline } from "../performance/building-baseline";
import { QualityControl } from "../performance/quality-control";
import { ReassignmentQueue } from "../performance/reassignment-queue";
import { ScoreDetails } from "../performance/score-details";
import { buildDashboardKpis } from "./dashboard-kpis";
import { buildBdDashboardKpis } from "./bd-dashboard-kpis";

const activities = [
  ["Lead moved to interviewing", "Sarah Ahmed · Senior Product Designer", "8 min ago", "info"],
  ["Interview scheduled", "Marcus Lee · Acme Systems", "24 min ago", "success"],
  ["Follow-up became overdue", "Priya Shah · Northstar Labs", "1 hr ago", "warning"],
  ["New application recorded", "Daniel Kim · Platform Engineer", "2 hrs ago", "neutral"],
] as const;

function activityLabel(value: string): string {
  return value
    .replaceAll("_", " ")
    .replaceAll(".", " · ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function entityLabel(value: string): string {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function DashboardOverview({ actor, dashboard, recentActivity, calendarInterviews, applications = [], openTasks = [], adminPerformance, performancePeriod = "30d", performanceMetric, performanceDrilldown, performanceReassignments = [], performanceReassignmentError, performanceOwners = [], onPerformanceReassign = async () => undefined, error }: { actor: SessionUser; dashboard?: DashboardData; recentActivity?: ActivityEventSummary[]; calendarInterviews?: InterviewSummary[]; applications?: LeadSummary[]; openTasks?: TaskSummary[]; adminPerformance?: AdminBdPerformanceResponse; performancePeriod?: PerformancePeriod; performanceMetric?: string; performanceDrilldown?: PerformanceDrilldownResponse; performanceReassignments?: PerformanceFollowUpWithLead[]; performanceReassignmentError?: string; performanceOwners?: UserSummary[]; onPerformanceReassign?: (formData: FormData) => void | Promise<void>; error?: string }) {
  const firstName = actor.displayName.split(" ")[0];
  const workspaceLabel = actor.role === "BD" ? "BD command center" : "Admin command center";
  const activityItems = recentActivity?.map((event) => [activityLabel(event.action), entityLabel(event.entityType), new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.occurredAt)), "info"] as const) ?? activities;
  const pulse = actor.role === "BD" ? buildBdDashboardKpis({ applications, openFollowUps: openTasks.length, interviewsToSchedule: applications.filter((application) => application.status === "RESPONSE_RECEIVED").length }).map((kpi) => [kpi.label, kpi.value, kpi.tone === "warning" ? "bg-warning-soft" : kpi.tone === "success" ? "bg-success-soft" : kpi.tone === "info" ? "bg-info-soft" : "bg-primary-soft", kpi.tone === "warning" ? "text-warning-foreground" : kpi.tone === "success" ? "text-success" : kpi.tone === "info" ? "text-info" : "text-primary", kpi.href] as const) : buildDashboardKpis(dashboard?.kpis ?? { applications: 0, responses: 0, interviews: 0, offers: 0, acceptedOffers: 0, placements: 0, starts: 0, activePipeline: 0, overdueTasks: 0, responseRate: null }, 0).map((kpi) => [kpi.label, kpi.value, kpi.tone === "warning" ? "bg-warning-soft" : kpi.tone === "success" ? "bg-success-soft" : kpi.tone === "info" ? "bg-info-soft" : "bg-primary-soft", kpi.tone === "warning" ? "text-warning-foreground" : kpi.tone === "success" ? "text-success" : kpi.tone === "info" ? "text-info" : "text-primary", kpi.href] as const);
  const sourceTotal = dashboard?.breakdowns.sources.reduce((sum, source) => sum + source.count, 0) ?? 0;
  const attentionCount = (dashboard?.kpis.overdueTasks ?? 0) + (dashboard?.kpis.interviews ?? 0 > 0 ? 0 : 1);
  return <div className="editorial-dashboard mx-auto max-w-[1500px]">
    <div className="editorial-hero"><div className="editorial-date-rail"><span className="editorial-date-number">{new Intl.DateTimeFormat("en-US", { day: "2-digit" }).format(new Date())}</span><span><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short", month: "long" }).format(new Date())}</strong><small>Week {Math.ceil(new Date().getDate() / 7)} · {new Date().getFullYear()}</small></span><a className="editorial-add-button" href="/leads">+ Add lead <span aria-hidden="true">›</span></a><a aria-label="Open calendar" className="editorial-round-button" href="/calendar">□</a></div><div className="editorial-greeting"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{workspaceLabel}</p><h1>Good morning, {firstName}</h1><p>Your entire placement operation, at a glance.</p></div></div>
    {error ? <p className="mt-4 rounded-xl border border-warning/30 bg-warning-soft px-4 py-3 text-sm text-warning-foreground" role="status">{error} Showing the last available workspace layout.</p> : null}
    <section aria-label="Workspace pulse" className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-foreground">Today’s operational pulse</h2><div className="editorial-filter-row"><span>Last 30 days⌄</span><span>All BDs⌄</span><span>All closers⌄</span><a aria-label="Open dashboard filters" href="/analytics">☷</a></div></div><div className="editorial-pulse-grid">{pulse.map(([label, value, iconTone, valueTone, href]) => <a aria-label={`${label}: ${value}`} className={`editorial-pulse-card ${label === "Needs review" && value > 0 ? "editorial-pulse-alert" : ""}`} href={href} key={label}><span className={`editorial-pulse-icon ${iconTone} ${valueTone}`}>{label === "Needs review" ? "!" : label === "Offers" ? "⌁" : label === "Interviews" ? "□" : "✓"}</span><span className="editorial-pulse-copy"><small>{label}</small><strong className={valueTone}>{value}</strong></span>{label === "Offers" ? <span className="editorial-sparkline" aria-hidden="true">⌁⌁⌁</span> : <span className="editorial-pulse-badge">{value > 0 ? "View" : "Clear"}</span>}</a>)}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,0.7fr)]"><section aria-label="Primary calendar"><CalendarWorkspace actor={actor} interviews={calendarInterviews ?? []} embedded /></section><Card aria-label="Needs attention" className="editorial-attention-card p-5 sm:p-6"><header className="flex items-center justify-between gap-3"><div><h2 className="text-base font-bold text-foreground">Needs attention <span className="editorial-count-pill">{attentionCount}</span></h2><p className="mt-1 text-xs text-muted-foreground">Small things that keep placements moving.</p></div><a className="editorial-today-pill" href="/tasks">Today · {dashboard?.kpis.overdueTasks ?? 0}</a></header><div className="mt-5 space-y-2.5">{(dashboard?.kpis.overdueTasks ?? 0) > 0 ? <a className="editorial-attention-item editorial-attention-danger" href="/tasks"><span className="editorial-status-dot bg-danger" /><span><strong>Overdue actions</strong><small>Follow-ups require a response.</small></span><b>{dashboard?.kpis.overdueTasks}</b></a> : null}<a className="editorial-attention-item" href="/calendar"><span className="editorial-status-dot bg-primary" /><span><strong>Calendar readiness</strong><small>{dashboard?.upcomingInterviews ?? 0} upcoming interviews in view.</small></span><b>→</b></a><a className="editorial-attention-item" href="/activity"><span className="editorial-status-dot bg-success" /><span><strong>Live activity</strong><small>{activityItems.length} recent operational updates.</small></span><b>→</b></a></div></Card></div>
    <section aria-label="Dashboard intelligence" className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(280px,0.85fr)_minmax(280px,0.85fr)]"><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Placement journey</h2><span className="editorial-today-pill">Last 30 days</span></header><div className="editorial-journey"><span className="journey-line" /><i /><i /><i /><i /></div><div className="editorial-journey-labels"><span>{dashboard?.kpis.applications ?? 0} applied</span><span>{dashboard?.kpis.interviews ?? 0} interviews</span><span>{dashboard?.kpis.offers ?? 0} offers</span><span>{dashboard?.kpis.placements ?? 0} placed</span></div></Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Application sources</h2><span className="editorial-today-pill">{sourceTotal} total</span></header>{dashboard?.breakdowns.sources.length ? <ul className="mt-5 space-y-3">{dashboard.breakdowns.sources.slice(0, 4).map((source) => <li className="flex items-center justify-between text-sm" key={source.key}><span className="text-muted-foreground">{source.key}</span><strong>{source.count}</strong></li>)}</ul> : <p className="mt-5 text-sm text-muted-foreground">Source mix will appear as applications are recorded.</p>}</Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Recent activity</h2><a className="text-xs font-semibold text-primary" href="/activity">View all</a></header><ol className="mt-5 space-y-3">{activityItems.slice(0, 3).map(([title, context, time, tone]) => <li className="flex gap-2.5" key={title}><span className={`mt-1.5 size-2 shrink-0 rounded-full ${tone === "warning" ? "bg-warning" : tone === "success" ? "bg-success" : "bg-primary"}`} /><span className="min-w-0"><strong className="block truncate text-xs text-foreground">{title}</strong><small className="block truncate text-[11px] text-muted-foreground">{context}</small><time className="mt-0.5 block text-[10px] text-muted-foreground">{time}</time></span></li>)}</ol></Card></section>
    {actor.role === "ADMIN" ? <Card className="mt-5 flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center sm:p-6"><div><h2 className="text-base font-semibold text-foreground">Employer operations</h2><p className="mt-1 text-sm text-muted-foreground">Maintain the employer directory used by applications and reporting.</p></div><a className="w-fit rounded-full bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground hover:bg-primary-hover" href="/admin/clients">Open employer directory</a></Card> : null}
    {actor.role === "ADMIN" && adminPerformance ? <section aria-label="Admin BD performance" className="mt-5 space-y-5"><BdTeamKpis performance={adminPerformance.team} period={performancePeriod} /><div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]"><BdLeaderboard period={performancePeriod} rows={adminPerformance.leaderboard} /><div className="space-y-5"><QualityControl quality={adminPerformance.quality} /><ReassignmentQueue error={performanceReassignmentError} followUps={performanceReassignments} onReassign={onPerformanceReassign} owners={performanceOwners} /></div></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]"><BuildingBaseline rows={adminPerformance.buildingBaseline} />{performanceMetric && performanceDrilldown ? <ScoreDetails items={performanceDrilldown} metric={performanceMetric} /> : <Card className="editorial-insight-card p-5 sm:p-6"><h2 className="text-base font-bold text-foreground">Score details</h2><p className="mt-1 text-sm text-muted-foreground">Choose any team performance KPI or row detail to inspect its exact Admin-authorized records.</p></Card>}</div></section> : null}
  </div>;
}
