import type { ActivityEventSummary, AdminBdPerformanceResponse, InterviewSummary, LeadSummary, PerformanceDrilldownResponse, PerformanceFollowUpWithLead, ProfileSummary, SessionUser, TaskSummary, UserSummary } from "@orbit/contracts";
import { Card } from "@orbit/ui";
import type { DashboardData } from "../../lib/api-client";
import { CalendarWorkspace } from "../calendar/calendar-workspace";
import { BdLeaderboard } from "../performance/bd-leaderboard";
import { BdTeamKpis, type PerformancePeriod } from "../performance/bd-team-kpis";
import { BuildingBaseline } from "../performance/building-baseline";
import { QualityControl } from "../performance/quality-control";
import { ReassignmentQueue } from "../performance/reassignment-queue";
import { ScoreDetails } from "../performance/score-details";
import { buildDashboardKpis } from "./dashboard-kpis";
import { buildBdDashboardKpis } from "./bd-dashboard-kpis";
import { BdApplicationEntry } from "./bd-application-entry";

const activities = [
  ["Lead moved to interviewing", "Sarah Ahmed · Senior Product Designer", "8 min ago", "info"],
  ["Interview scheduled", "Marcus Lee · Acme Systems", "24 min ago", "success"],
  ["Follow-up became overdue", "Priya Shah · Northstar Labs", "1 hr ago", "warning"],
  ["New application recorded", "Daniel Kim · Platform Engineer", "2 hrs ago", "neutral"],
] as const;

function activityLabel(value: string): string {
  return value
    .replaceAll("_", " ")
    .replaceAll(".", " · ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function entityLabel(value: string): string {
  return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function BdDashboard({ actor, applications, openTasks, interviews, profiles, error }: { actor: SessionUser; applications: LeadSummary[]; openTasks: TaskSummary[]; interviews: InterviewSummary[]; profiles: ProfileSummary[]; error?: string }) {
  const now = new Date();
  const today = new Intl.DateTimeFormat("en-CA").format(now);
  const addedToday = applications.filter((application) => application.appliedDate === today).length;
  const target = 70;
  const responses = applications.filter((application) => application.status === "RESPONSE_RECEIVED");
  const active = applications.filter((application) => ["INTERVIEWING", "OFFER_RECEIVED", "OFFER_ACCEPTED", "PLACED"].includes(application.status));
  const upcoming = interviews.filter((interview) => new Date(interview.startsAt) >= now).sort((a, b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime()).slice(0, 5);
  const kpis = [
    ["Applications today", addedToday, "bg-primary-soft", "text-primary", `Target ${target}`],
    ["Remaining target", Math.max(0, target - addedToday), "bg-warning-soft", "text-warning-foreground", "To reach 70"],
    ["Recruiter responses", responses.length, "bg-info-soft", "text-info", "Needs review"],
    ["Interviews to schedule", responses.length, "bg-danger-soft", "text-danger", "Open response queue"],
  ] as const;
  const platformCounts = new Map<string, number>();
  applications.forEach((application) => { try { const host = new URL(application.rawUrl).hostname.replace(/^www\./, ""); platformCounts.set(host, (platformCounts.get(host) ?? 0) + 1); } catch { platformCounts.set("Other", (platformCounts.get("Other") ?? 0) + 1); } });
  return <div aria-label="BD application workspace" className="editorial-dashboard mx-auto max-w-[1500px]">
    <div className="editorial-hero"><div className="editorial-date-rail"><span className="editorial-date-number">{new Intl.DateTimeFormat("en-US", { day: "2-digit" }).format(now)}</span><span><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short", month: "long" }).format(now)}</strong><small>Daily target · {target}</small></span><BdApplicationEntry actorId={actor.id} profiles={profiles} /></div><div className="editorial-greeting"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">BD application desk</p><h1>Good morning, {actor.displayName.split(" ")[0]}</h1><p>Keep applications moving from entry to recruiter response.</p></div></div>
    {error ? <p className="mt-4 rounded-xl border border-warning/30 bg-warning-soft px-4 py-3 text-sm text-warning-foreground" role="status">{error}</p> : null}
    <section aria-label="BD application pulse" className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-foreground">Application pulse</h2><a className="text-xs font-semibold text-primary" href="/leads">Open all applications →</a></div><div className="editorial-pulse-grid">{kpis.map(([label, value, iconTone, valueTone, hint]) => <a aria-label={`${label}: ${value}`} className="editorial-pulse-card" href={label === "Recruiter responses" || label === "Interviews to schedule" ? "/leads?status=RESPONSE_RECEIVED" : "/leads"} key={label}><span className={`editorial-pulse-icon ${iconTone} ${valueTone}`}>{label === "Recruiter responses" ? "↗" : label === "Interviews to schedule" ? "!" : "✓"}</span><span className="editorial-pulse-copy"><small>{label}</small><strong className={valueTone}>{value}</strong></span><span className="editorial-pulse-badge">{hint}</span></a>)}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,0.65fr)]"><Card aria-label="BD work queue" className="editorial-attention-card p-5 sm:p-6"><header className="flex items-center justify-between"><div><h2 className="text-base font-bold text-foreground">Work queue</h2><p className="mt-1 text-xs text-muted-foreground">The next operational handoffs.</p></div><a className="editorial-today-pill" href="/tasks">{openTasks.length} tasks</a></header><div className="mt-5 space-y-2.5"><a className="editorial-attention-item editorial-attention-danger" href="/leads?status=RESPONSE_RECEIVED"><span className="editorial-status-dot bg-danger" /><span><strong>Recruiter responses</strong><small>Review and schedule interviews.</small></span><b>{responses.length}</b></a><a className="editorial-attention-item" href="/leads?status=INTERVIEWING"><span className="editorial-status-dot bg-primary" /><span><strong>Active applications</strong><small>Already moving through the funnel.</small></span><b>{active.length}</b></a><a className="editorial-attention-item" href="/tasks"><span className="editorial-status-dot bg-warning" /><span><strong>Follow-ups due</strong><small>Keep recruiter conversations warm.</small></span><b>{openTasks.length}</b></a></div></Card></div>
    <section aria-label="BD operations" className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(280px,0.65fr)]"><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><div><h2 className="text-base font-bold text-foreground">Recent applications</h2><p className="mt-1 text-xs text-muted-foreground">Latest entries needing a quick check.</p></div><a className="text-xs font-semibold text-primary" href="/leads">View all</a></header><div className="mt-4 divide-y divide-border">{applications.slice(0, 6).map((application) => <a className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0 hover:bg-surface-subtle" href={`/leads/${application.id}`} key={application.id}><span className="min-w-0"><strong className="block truncate text-sm text-foreground">{application.jobTitle}</strong><small className="block truncate text-xs text-muted-foreground">{application.companyName ?? "Company not recorded"} · {application.appliedDate}</small></span><span className="shrink-0 rounded-full bg-info-soft px-2.5 py-1 text-[10px] font-bold uppercase text-info">{application.status.replaceAll("_", " ")}</span></a>)}{applications.length === 0 ? <p className="py-5 text-sm text-muted-foreground">Your application entries will appear here.</p> : null}</div></Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><div><h2 className="text-base font-bold text-foreground">Upcoming interviews</h2><p className="mt-1 text-xs text-muted-foreground">Compact handoff view.</p></div><a className="text-xs font-semibold text-primary" href="/?calendarView=week">Dashboard calendar</a></header>{upcoming.length ? <ol className="mt-4 space-y-3">{upcoming.map((interview) => <li className="flex items-start justify-between gap-3" key={interview.id}><span className="min-w-0"><strong className="block truncate text-sm text-foreground">{interview.roundType.replaceAll("_", " ")}</strong><small className="block text-xs text-muted-foreground">{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "Asia/Karachi" }).format(new Date(interview.startsAt))} PKT</small></span><span className="rounded-full bg-primary-soft px-2 py-1 text-[10px] font-bold text-primary">{interview.status}</span></li>)}</ol> : <p className="mt-5 text-sm text-muted-foreground">No upcoming interviews.</p>}</Card></section>
    <section aria-label="BD insights" className="mt-5 grid gap-5 md:grid-cols-2"><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Applications by platform</h2><span className="editorial-today-pill">{applications.length} total</span></header><ul className="mt-4 space-y-3">{Array.from(platformCounts.entries()).slice(0, 5).map(([platform, count]) => <li className="flex items-center justify-between text-sm" key={platform}><span className="text-muted-foreground">{platform}</span><strong>{count}</strong></li>)}</ul></Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">What needs attention</h2><a className="text-xs font-semibold text-primary" href="/activity">Activity</a></header><p className="mt-4 text-sm leading-6 text-muted-foreground">Recruiter replies become active applications. Review the response, add the interview details, then hand the scheduled call to the assigned Closer.</p></Card></section>
  </div>;
}

export function DashboardOverview({ actor, dashboard, recentActivity, calendarInterviews, applications = [], openTasks = [], calendarLeads = [], calendarClosers = [], profiles = [], adminPerformance, performancePeriod = "30d", performanceMetric, performanceDrilldown, performanceReassignments = [], performanceReassignmentError, performanceOwners = [], onPerformanceReassign = async () => undefined, error }: { actor: SessionUser; dashboard?: DashboardData; recentActivity?: ActivityEventSummary[]; calendarInterviews?: InterviewSummary[]; applications?: LeadSummary[]; openTasks?: TaskSummary[]; calendarLeads?: LeadSummary[]; calendarClosers?: UserSummary[]; profiles?: ProfileSummary[]; adminPerformance?: AdminBdPerformanceResponse; performancePeriod?: PerformancePeriod; performanceMetric?: string; performanceDrilldown?: PerformanceDrilldownResponse; performanceReassignments?: PerformanceFollowUpWithLead[]; performanceReassignmentError?: string; performanceOwners?: UserSummary[]; onPerformanceReassign?: (formData: FormData) => void | Promise<void>; error?: string }) {
  const firstName = actor.displayName.split(" ")[0];
  const workspaceLabel = actor.role === "BD" ? "BD command center" : "Admin command center";
  const activityItems = recentActivity?.map((event) => [activityLabel(event.action), entityLabel(event.entityType), new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.occurredAt)), "info"] as const) ?? activities;
  const pulse = actor.role === "BD" ? buildBdDashboardKpis({ applications, openFollowUps: openTasks.length, interviewsToSchedule: applications.filter((application) => application.status === "RESPONSE_RECEIVED").length }).map((kpi) => [kpi.label, kpi.value, kpi.tone === "warning" ? "bg-warning-soft" : kpi.tone === "success" ? "bg-success-soft" : kpi.tone === "info" ? "bg-info-soft" : "bg-primary-soft", kpi.tone === "warning" ? "text-warning-foreground" : kpi.tone === "success" ? "text-success" : kpi.tone === "info" ? "text-info" : "text-primary", kpi.href] as const) : buildDashboardKpis(dashboard?.kpis ?? { applications: 0, responses: 0, interviews: 0, offers: 0, acceptedOffers: 0, placements: 0, starts: 0, activePipeline: 0, overdueTasks: 0, responseRate: null }, 0).map((kpi) => [kpi.label, kpi.value, kpi.tone === "warning" ? "bg-warning-soft" : kpi.tone === "success" ? "bg-success-soft" : kpi.tone === "info" ? "bg-info-soft" : "bg-primary-soft", kpi.tone === "warning" ? "text-warning-foreground" : kpi.tone === "success" ? "text-success" : kpi.tone === "info" ? "text-info" : "text-primary", kpi.href] as const);
  const sourceTotal = dashboard?.breakdowns.sources.reduce((sum, source) => sum + source.count, 0) ?? 0;
  const sourceMax = Math.max(1, ...(dashboard?.breakdowns.sources.map((source) => source.count) ?? []));
  const attentionCount = dashboard?.kpis.overdueTasks ?? 0;
  if (actor.role === "BD") return <BdDashboard actor={actor} applications={applications} openTasks={openTasks} interviews={calendarInterviews ?? []} profiles={profiles} error={error} />;
  return <div className="admin-surface-system editorial-dashboard mx-auto max-w-[1500px]">
    <div className="editorial-hero"><div className="editorial-date-rail"><span className="editorial-date-number">{new Intl.DateTimeFormat("en-US", { day: "2-digit" }).format(new Date())}</span><span><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short", month: "long" }).format(new Date())}</strong><small>Week {Math.ceil(new Date().getDate() / 7)} · {new Date().getFullYear()}</small></span><a className="editorial-add-button" href="/candidates?new=candidate">+ Add candidate <span aria-hidden="true">›</span></a></div><div className="editorial-greeting"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{workspaceLabel}</p><h1>Good morning, {firstName}</h1><p>Your entire placement operation, at a glance.</p></div></div>
    {error ? <p className="mt-4 rounded-xl border border-warning/30 bg-warning-soft px-4 py-3 text-sm text-warning-foreground" role="status">{error} Showing the last available workspace layout.</p> : null}
    <section aria-label="Workspace pulse" className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-foreground">Today’s operational pulse</h2><div className="editorial-filter-row"><span>Last 30 days⌄</span><span>All BDs⌄</span><span>All closers⌄</span><a aria-label="Open dashboard filters" href="/analytics">☷</a></div></div><div className="editorial-pulse-grid">{pulse.map(([label, value, iconTone, valueTone, href]) => <a aria-label={`${label}: ${value}`} className={`editorial-pulse-card ${label === "Needs review" && value > 0 ? "editorial-pulse-alert" : ""}`} href={href} key={label}><span className={`editorial-pulse-icon ${iconTone} ${valueTone}`}>{label === "Needs review" ? "!" : label === "Offers" ? "⌁" : label === "Interviews" ? "□" : "✓"}</span><span className="editorial-pulse-copy"><small>{label}</small><strong className={valueTone}>{value}</strong></span>{label === "Offers" ? <span className="editorial-sparkline" aria-hidden="true">⌁⌁⌁</span> : <span className="editorial-pulse-badge">{value > 0 ? "View" : "Clear"}</span>}</a>)}</div></section>
    <div className="mt-5 grid items-start gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,0.7fr)]"><section aria-label="Primary calendar"><CalendarWorkspace actor={actor} interviews={calendarInterviews ?? []} leads={calendarLeads} closers={calendarClosers} embedded /></section><Card aria-label="Needs attention" className="editorial-attention-card p-5 sm:p-6"><header className="flex items-center justify-between gap-3"><div><h2 className="text-base font-bold text-foreground">Needs attention <span className={`editorial-count-pill ${attentionCount === 0 ? "is-clear" : ""}`}>{attentionCount === 0 ? "Clear" : attentionCount}</span></h2><p className="mt-1 text-xs text-muted-foreground">Small things that keep placements moving.</p></div><a className="editorial-today-pill" href="/tasks">Today</a></header><div className="mt-5 space-y-2.5">{attentionCount > 0 ? <a className="editorial-attention-item editorial-attention-danger" href="/tasks"><span className="editorial-status-dot bg-danger" /><span><strong>Overdue actions</strong><small>Follow-ups require a response.</small></span><b>{attentionCount}</b></a> : <div className="editorial-attention-clear"><span>✓</span><p><strong>Queue is clear</strong><small>No overdue actions right now.</small></p></div>}<a className="editorial-attention-item" href="/?calendarView=day"><span className="editorial-status-dot bg-primary" /><span><strong>Calendar readiness</strong><small>{dashboard?.upcomingInterviews ?? 0} upcoming interviews in view.</small></span><b>→</b></a><a className="editorial-attention-item" href="/activity"><span className="editorial-status-dot bg-success" /><span><strong>Live activity</strong><small>{activityItems.length} recent operational updates.</small></span><b>→</b></a></div></Card></div>
    <section aria-label="Dashboard intelligence" className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(280px,0.85fr)_minmax(280px,0.85fr)]"><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Placement journey</h2><span className="editorial-today-pill">Last 30 days</span></header><div className="editorial-funnel" aria-label="Placement funnel"><span><strong>{dashboard?.kpis.applications ?? 0}</strong><small>Applied</small></span><span><strong>{dashboard?.kpis.interviews ?? 0}</strong><small>Interviews</small></span><span><strong>{dashboard?.kpis.offers ?? 0}</strong><small>Offers</small></span><span><strong>{dashboard?.kpis.placements ?? 0}</strong><small>Placed</small></span></div></Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Application sources</h2><span className="editorial-today-pill">{sourceTotal} total</span></header>{dashboard?.breakdowns.sources.length ? <ul aria-label="Application source distribution" className="mt-5 space-y-3">{dashboard.breakdowns.sources.slice(0, 4).map((source, index) => <li key={source.key}><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate text-muted-foreground">{source.key}</span><strong>{source.count}</strong></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-surface-subtle"><span className="block h-full rounded-full" style={{ backgroundColor: ["#e85f43", "#f08a64", "#d9953f", "#bd6d57"][index], width: `${Math.max(8, (source.count / sourceMax) * 100)}%` }} /></div></li>)}</ul> : <p className="mt-5 text-sm text-muted-foreground">Source mix will appear as applications are recorded.</p>}</Card><Card className="editorial-insight-card p-5 sm:p-6"><header className="flex items-center justify-between"><h2 className="text-base font-bold text-foreground">Recent activity</h2><a className="text-xs font-semibold text-primary" href="/activity">View all</a></header><ol className="mt-5 space-y-3">{activityItems.slice(0, 3).map(([title, context, time, tone], index) => <li className="flex gap-2.5" key={`${title}-${context}-${time}-${index}`}><span className={`mt-1.5 size-2 shrink-0 rounded-full ${tone === "warning" ? "bg-warning" : tone === "success" ? "bg-success" : "bg-primary"}`} /><span className="min-w-0"><strong className="block truncate text-xs text-foreground">{title}</strong><small className="block truncate text-[11px] text-muted-foreground">{context}</small><time className="mt-0.5 block text-[10px] text-muted-foreground">{time}</time></span></li>)}</ol></Card></section>
    {actor.role === "ADMIN" && adminPerformance ? <section aria-label="Admin BD performance" className="mt-5 space-y-5"><BdTeamKpis performance={adminPerformance.team} period={performancePeriod} /><div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,0.85fr)]"><div className="space-y-5"><BdLeaderboard period={performancePeriod} rows={adminPerformance.leaderboard} /><BuildingBaseline rows={adminPerformance.buildingBaseline} /></div><div className="space-y-5"><QualityControl quality={adminPerformance.quality} /><ReassignmentQueue error={performanceReassignmentError} followUps={performanceReassignments} onReassign={onPerformanceReassign} owners={performanceOwners} />{performanceMetric && performanceDrilldown ? <ScoreDetails items={performanceDrilldown} metric={performanceMetric} /> : <Card className="editorial-insight-card admin-score-details p-5 sm:p-6"><h2 className="text-base font-bold text-foreground">Score details</h2><p className="mt-1 text-sm text-muted-foreground">Choose a KPI or leaderboard row to inspect the exact records behind its score.</p></Card>}</div></div></section> : null}
  </div>;
}
