import { Body, Controller, Delete, Get, Inject, Optional, Param, Patch, Post, Query, Req, UseGuards } from "@nestjs/common";
import { AuthenticationError, CollaborationService, LeadsService, NotificationsService, PerformanceService, ValidationError } from "@orbit/backend";
import { archiveCommunicationSchema, archiveLeadSchema, assignLeadCloserRequestSchema, communicationListQuerySchema, companyListQuerySchema, contactListQuerySchema, createApplicationIntakeSchema, createCommentSchema, createCommunicationSchema, createCompanyCloserAssignmentSchema, createCompanySchema, createContactSchema, createLeadSchema, leadListQuerySchema, leadStatusTransitionSchema, restoreLeadSchema, setLeadImportantSchema, transferLeadOwnershipSchema, updateCommentSchema, updateCommunicationRequestSchema, updateCompanyRequestSchema, updateContactRequestSchema, updateLeadRequestSchema, uuidSchema } from "@orbit/contracts";
import { IdentityGuard, type AuthenticatedRequest } from "../identity/identity.guard";

type Schema<T> = { safeParse(value: unknown): { success: true; data: T } | { success: false; error: { issues: unknown } } };
function parse<T>(schema: Schema<T>, value: unknown): T { const parsed = schema.safeParse(value); if (!parsed.success) throw new ValidationError("The request payload is invalid", parsed.error.issues); return parsed.data; }

@Controller("leads")
@UseGuards(IdentityGuard)
export class LeadsController {
  constructor(@Inject(LeadsService) private readonly leads: LeadsService, @Inject(CollaborationService) private readonly collaboration: CollaborationService, @Inject(NotificationsService) private readonly notifications: NotificationsService, @Optional() @Inject(PerformanceService) private readonly performance?: PerformanceService) {}
  @Get("/companies") companies(@Query() query: unknown, @Req() request: AuthenticatedRequest) { return this.leads.listCompanies(this.actor(request), parse(companyListQuerySchema, query)); }
  @Post("/companies") createCompany(@Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.leads.createCompany(this.actor(request), parse(createCompanySchema, input)); }
  @Patch("/companies/:companyId") updateCompany(@Param("companyId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(updateCompanyRequestSchema, input); const { expectedVersion, ...changes } = value; return this.leads.updateCompany(this.actor(request), parse(uuidSchema, id), changes, expectedVersion); }
  @Get("/companies/:companyId/closers") companyClosers(@Param("companyId") id: string, @Req() request: AuthenticatedRequest) { return this.leads.listCompanyClosers(this.actor(request), parse(uuidSchema, id)); }
  @Post("/companies/:companyId/closers") assignCompanyCloser(@Param("companyId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(createCompanyCloserAssignmentSchema, input); return this.leads.assignCompanyCloser(this.actor(request), parse(uuidSchema, id), value.closerId); }
  @Delete("/companies/:companyId/closers/:closerId") removeCompanyCloser(@Param("companyId") id: string, @Param("closerId") closerId: string, @Req() request: AuthenticatedRequest) { return this.leads.removeCompanyCloser(this.actor(request), parse(uuidSchema, id), parse(uuidSchema, closerId)); }
  @Get("/contacts") contacts(@Query() query: unknown, @Req() request: AuthenticatedRequest) { return this.leads.listContacts(this.actor(request), parse(contactListQuerySchema, query)); }
  @Post("/contacts") createContact(@Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.leads.createContact(this.actor(request), parse(createContactSchema, input)); }
  @Patch("/contacts/:contactId") updateContact(@Param("contactId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(updateContactRequestSchema, input); const { expectedVersion, ...changes } = value; return this.leads.updateContact(this.actor(request), parse(uuidSchema, id), changes, expectedVersion); }
  @Get() list(@Query() query: unknown, @Req() request: AuthenticatedRequest) { return this.leads.list(this.actor(request), parse(leadListQuerySchema, query)); }
  @Post("/intake") async createApplicationIntake(@Body() input: unknown, @Req() request: AuthenticatedRequest) { const intake = await this.leads.createApplicationIntake(this.actor(request), parse(createApplicationIntakeSchema, input)); await this.notifications.createInApp({ idempotencyKey: `lead-created:${intake.lead.id}`, recipientUserId: intake.lead.currentOwnerId, title: "New application recorded", message: intake.lead.jobTitle, relatedEntityType: "lead", relatedEntityId: intake.lead.id }); return intake; }
  @Post() async create(@Body() input: unknown, @Req() request: AuthenticatedRequest) { const lead = await this.leads.create(this.actor(request), parse(createLeadSchema, input)); await this.notifications.createInApp({ idempotencyKey: `lead-created:${lead.id}`, recipientUserId: lead.currentOwnerId, title: "New lead assigned", message: lead.jobTitle, relatedEntityType: "lead", relatedEntityId: lead.id }); return lead; }
  @Get(":leadId") get(@Param("leadId") id: string, @Req() request: AuthenticatedRequest) { return this.leads.get(this.actor(request), parse(uuidSchema, id)); }
  @Patch(":leadId") update(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(updateLeadRequestSchema, input); const { expectedVersion, ...changes } = value; return this.leads.update(this.actor(request), parse(uuidSchema, id), changes, expectedVersion); }
  @Post(":leadId/status") async status(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const actor = this.actor(request); const value = parse(leadStatusTransitionSchema, input); const lead = await this.leads.transition(actor, parse(uuidSchema, id), value.toStatus, value.reason, value.expectedVersion); if (value.toStatus === "RESPONSE_RECEIVED") await this.performance?.recordRecruiterResponse(actor, lead.id); return lead; }
  @Post(":leadId/transfer") async transfer(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(transferLeadOwnershipSchema, input); const lead = await this.leads.transfer(this.actor(request), parse(uuidSchema, id), value.newOwnerId, value.reason, value.expectedVersion); await this.notifications.createInApp({ idempotencyKey: `lead-transferred:${lead.id}:${lead.version}`, recipientUserId: lead.currentOwnerId, title: "Lead transferred to you", message: lead.jobTitle, relatedEntityType: "lead", relatedEntityId: lead.id }); return lead; }
  @Post(":leadId/important") important(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(setLeadImportantSchema, input); return this.leads.setImportant(this.actor(request), parse(uuidSchema, id), value.important, value.expectedVersion); }
  @Post(":leadId/closer") closer(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(assignLeadCloserRequestSchema, input); return this.leads.assignCloser(this.actor(request), parse(uuidSchema, id), value.closerId, value.expectedVersion); }
  @Post(":leadId/archive") archive(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(archiveLeadSchema, input); return this.leads.archive(this.actor(request), parse(uuidSchema, id), value.reason, value.expectedVersion); }
  @Post(":leadId/restore") restore(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(restoreLeadSchema, input); return this.leads.restore(this.actor(request), parse(uuidSchema, id), value.reason, value.expectedVersion); }
  @Get(":leadId/communications") communications(@Param("leadId") id: string, @Query() query: unknown, @Req() request: AuthenticatedRequest) { return this.collaboration.listCommunications(this.actor(request), parse(uuidSchema, id), parse(communicationListQuerySchema, query)); }
  @Post(":leadId/communications") createCommunication(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.collaboration.createCommunication(this.actor(request), parse(uuidSchema, id), parse(createCommunicationSchema, input)); }
  @Get(":leadId/comments") comments(@Param("leadId") id: string, @Req() request: AuthenticatedRequest) { return this.collaboration.listComments(this.actor(request), parse(uuidSchema, id)); }
  @Post(":leadId/comments") createComment(@Param("leadId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.collaboration.createComment(this.actor(request), parse(uuidSchema, id), parse(createCommentSchema, input)); }
  @Patch("/communications/:communicationId") updateCommunication(@Param("communicationId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(updateCommunicationRequestSchema, input); const { expectedVersion, ...changes } = value; return this.collaboration.updateCommunication(this.actor(request), parse(uuidSchema, id), changes, expectedVersion); }
  @Post("/communications/:communicationId/archive") archiveCommunication(@Param("communicationId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { const value = parse(archiveCommunicationSchema, input); return this.collaboration.archiveCommunication(this.actor(request), parse(uuidSchema, id), value.reason); }
  @Patch("/comments/:commentId") updateComment(@Param("commentId") id: string, @Body() input: unknown, @Req() request: AuthenticatedRequest) { return this.collaboration.updateComment(this.actor(request), parse(uuidSchema, id), parse(updateCommentSchema, input)); }
  private actor(request: AuthenticatedRequest) { if (!request.actor) throw new AuthenticationError(); return request.actor; }
}
