"use client";

import { useState } from "react";

import { Button, Card, Input } from "@orbit/ui";
import { createLeadOffer, updateOffer } from "../../lib/api-client";
import type { OfferSummary } from "@orbit/contracts";

export function OfferForm({ leadId, offer }: { leadId: string; offer?: OfferSummary }) {
  const [amount, setAmount] = useState(offer?.compensationAmount ?? ""); const [currency, setCurrency] = useState(offer?.compensationCurrency ?? "USD"); const [employmentType, setEmploymentType] = useState(offer?.employmentType ?? "Full-time"); const [details, setDetails] = useState(offer?.details ?? ""); const [deadline, setDeadline] = useState(offer?.decisionDeadline?.slice(0, 16) ?? ""); const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); try { const input = { compensationAmount: amount, compensationCurrency: currency, employmentType, details, ...(deadline ? { decisionDeadline: new Date(deadline).toISOString() } : {}) }; if (offer) await updateOffer(offer.id, { ...input, expectedVersion: offer.version }); else await createLeadOffer(leadId, input); window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Offer could not be saved."); } finally { setPending(false); } }
  return <Card className="p-5"><h2 className="text-base font-bold text-foreground">{offer ? "Edit offer" : "Create offer"}</h2><form className="mt-4 grid gap-3" onSubmit={submit}><div className="grid gap-3 sm:grid-cols-3"><label className="sr-only" htmlFor={`amount-${offer?.id ?? leadId}`}>Compensation amount</label><Input id={`amount-${offer?.id ?? leadId}`} inputMode="decimal" onChange={(event) => setAmount(event.target.value)} placeholder="Compensation" value={amount} /><label className="sr-only" htmlFor={`currency-${offer?.id ?? leadId}`}>Currency</label><Input id={`currency-${offer?.id ?? leadId}`} maxLength={3} onChange={(event) => setCurrency(event.target.value.toUpperCase())} placeholder="Currency" value={currency} /><label className="sr-only" htmlFor={`employment-${offer?.id ?? leadId}`}>Employment type</label><Input id={`employment-${offer?.id ?? leadId}`} onChange={(event) => setEmploymentType(event.target.value)} placeholder="Employment type" value={employmentType} /></div><label className="sr-only" htmlFor={`details-${offer?.id ?? leadId}`}>Offer details</label><textarea className="min-h-24 rounded-xl border border-border bg-surface px-3.5 py-3 text-sm text-foreground" id={`details-${offer?.id ?? leadId}`} onChange={(event) => setDetails(event.target.value)} placeholder="Offer details" value={details} /><label className="text-sm font-semibold text-foreground" htmlFor={`deadline-${offer?.id ?? leadId}`}>Decision deadline (optional)</label><Input id={`deadline-${offer?.id ?? leadId}`} onChange={(event) => setDeadline(event.target.value)} type="datetime-local" value={deadline} /><div className="flex items-center gap-3"><Button disabled={pending || !amount || !details} type="submit">{pending ? "Saving…" : offer ? "Save offer" : "Create offer"}</Button>{error ? <p className="text-sm font-semibold text-danger" role="alert">{error}</p> : null}</div></form></Card>;
}
