"use client";
import { useState } from "react";
import { Button, Field, Input } from "@orbit/ui";
import { completePasswordReset, requestPasswordReset } from "../../lib/api-client";

export function PasswordResetForm({ token }: { token?: string }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); try { if (token) { if (password !== confirmation) throw new Error("Passwords must match."); await completePasswordReset(token, password); setMessage("Password updated. You can now sign in."); } else { const result = await requestPasswordReset(email); setMessage(result.token ? `Reset link: ${window.location.origin}/reset-password?token=${result.token}` : "If that account exists, reset instructions are ready."); } } catch (cause) { setError(cause instanceof Error ? cause.message : "The password reset request failed."); } finally { setPending(false); } }
  return <form className="grid gap-5" onSubmit={submit}>{token ? <><Field htmlFor="new-password" label="New password"><Input id="new-password" minLength={12} required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></Field><Field htmlFor="confirm-password" label="Confirm password"><Input id="confirm-password" minLength={12} required type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></Field></> : <Field htmlFor="reset-email" label="Work email"><Input id="reset-email" required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></Field>}{error ? <p className="text-sm font-semibold text-danger" role="alert">{error}</p> : null}{message ? <p className="break-all text-sm font-semibold text-success" role="status">{message}</p> : null}<Button disabled={pending} type="submit">{pending ? "Working…" : token ? "Reset password" : "Send reset instructions"}</Button></form>;
}
